### ISSUE TITLE
'fixed' type broken: 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by leftys** [fastavro/fastavro#209]
Hi, 

I am serializing an *uint64_t* as *fixed* type: 
`{'name': 'time_int_field', 'type': {'name': 'time_int_field', 'type': 'fixed', 'size': 8}, 'default': bytes(8)},`
and then i serialize the record like 
`'time_int_field': raw.time_int_field.to_bytes(8, byteorder = 'big'),`
This works in 0.17.7, but not in 0.17.10. In the latter version, the following exception is raised:

```
  File "/home/jan_cespivo/projects/quantlane/ingress/ingress/dumpers/base.py", line 32, in reset
    self.open_file()
  File "/home/jan_cespivo/projects/quantlane/ingress/ingress/dumpers/avro.py", line 68, in open_file
    validator = True
  File "fastavro/_write.pyx", line 753, in fastavro._write.Writer.__init__
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

It seems that even the default value is causing trouble. By the way, is this the correct way to use *fixed* types or store *uint64_t*?

**Comment by leftys** [comment]
Update: if I change the default from `bytes(8)` to `8*'\x00'`, all works.

**Comment by scottbelden** [comment]
Interesting. The thing that changed is we stopped using `ujson`. It looks like `ujson` automatically decoded the bytes type when serializing:

```python
In [4]: ujson.dumps({'a': bytes(1)})
Out[4]: '{"a":"\\u0000"}'
```

Whereas the builtin `json` module doesn't do this:

```python
In [3]: json.dumps({'a': bytes(1)})
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-ce21baf0a4db> in <module>()
----> 1 json.dumps({'a': bytes(1)})

/usr/lib/python3.6/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    229         cls is None and indent is None and separators is None and
    230         default is None and not sort_keys and not kw):
--> 231         return _default_encoder.encode(obj)
    232     if cls is None:
    233         cls = JSONEncoder

/usr/lib/python3.6/json/encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

/usr/lib/python3.6/json/encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

/usr/lib/python3.6/json/encoder.py in default(self, o)
    178         """
    179         raise TypeError("Object of type '%s' is not JSON serializable" %
--> 180                         o.__class__.__name__)
    181 
    182     def encode(self, o):

TypeError: Object of type 'bytes' is not JSON serializable
```

The use of `8 * '\x00` will work, but I think it might be a little more obvious to do something like `bytes(8).decode('utf-8')` (Or maybe `iso-8859-1` as that is what the apache java uses in at least their json encoder/decoder: https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/io/JsonDecoder.java#L64).

I'm curious what the avro compiler would produce for the schema if the `avdl` file has a `fixed` or `bytes` type with the default value you mentioned. I would expect something along the lines of `'\x00\x00\x00\x00\x00\x00\x00\x00'` but we should probably verify.

**Comment by scottbelden** [comment]
By the way, this is similar to https://github.com/tebeka/fastavro/issues/69
