### ISSUE TITLE
I'm trying to debug an issue I'm having atm with some complex data structures, but I couldn't make pdb work within _write_py.py

### ISSUE THREAD

**Issue by IceS2** [fastavro/fastavro#252]
The error is: 
```
Traceback (most recent call last):
  File "fastavro/_write.pyx", line 454, in fastavro._write.write_record
TypeError: Expected dict, got str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_avro.py", line 12, in <module>
    writer(out, parsed_schema, json_message)
  File "fastavro/_write.pyx", line 691, in fastavro._write.writer
  File "fastavro/_write.pyx", line 663, in fastavro._write.Writer.write
  File "fastavro/_write.pyx", line 535, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 463, in fastavro._write.write_record
AttributeError: 'str' object has no attribute 'get'
```

I've tried to see if some data type as miss mapped but I couldn't find an error, I'd love some help either by haviing some extra eyes to  pass through the extensive json or to  help me with the debugger issue.

schema
```
{
  "name": "jobs",
  "namespace": "levee.datalake",
  "doc": "",
  "type": "record",
  "fields": [
    {
      "name": "headers",
      "type": {
        "name": "headers_def",
        "namespace": "levee.datalake.headers",
        "doc": "",
        "type": "record",
        "fields": [
          {
            "name": "appName",
            "type": "string"
          },
          {
            "name": "resource",
            "type": "string"
          },
          {
            "name": "origin",
            "type": "string"
          },
          {
            "name": "action",
            "type": "string"
          },
          {
            "name": "schemaVersion",
            "type": "float"
          }
        ]
      }
    },
    {
      "name": "body",
      "type": {
        "name": "body_def",
        "namespace": "levee.datalake.body",
        "doc": "",
        "type": "record",
        "fields": [
          {
            "name": "id",
            "type": "int"
          },
          {
            "name": "title",
            "type": "string"
          },
          {
            "name": "alternative_name",
            "type": "string"
          },
          {
            "name": "category",
            "type": "int"
          },
          {
            "name": "position",
            "type": "int"
          },
          {
            "name": "experience",
            "type": "int"
          },
          {
            "name": "drivers_license",
            "type": {
              "type": "array",
              "items": "null"
            }
          },
          {
            "name": "description",
            "type": "string"
          },
          {
            "name": "short_description",
            "type": "string"
          },
          {
            "name": "available_at",
            "type": "null"
          },
          {
            "name": "close_at",
            "type": "null"
          },
          {
            "name": "created_by",
            "type": {
              "name": "created_by_def",
              "namespace": "levee.datalake.body.created_by",
              "doc": "",
              "type": "record",
              "fields": [
                {
                  "name": "id",
                  "type": "int"
                },
                {
                  "name": "rank",
                  "type": "string"
                },
                {
                  "name": "branch_id",
                  "type": "null"
                },
                {
                  "name": "recruiter",
                  "type": "boolean"
                },
                {
                  "name": "role_type",
                  "type": "string"
                },
                {
                  "name": "user_name",
                  "type": "string"
                },
                {
                  "name": "company_id",
                  "type": "int"
                }
              ]
            }
          },
          {
            "name": "state",
            "type": "string"
          },
          {
            "name": "company_id",
            "type": "int"
          },
          {
            "name": "company_name",
            "type": "string"
          },
          {
            "name": "branch_id",
            "type": "int"
          },
          {
            "name": "candidates",
            "type": "int"
          },
          {
            "name": "candidates_requested",
            "type": "int"
          },
          {
            "name": "schedule_type",
            "type": "string"
          },
          {
            "name": "gender",
            "type": "string"
          },
          {
            "name": "age",
            "type": {
              "name": "age_def",
              "namespace": "levee.datalake.body.age",
              "doc": "",
              "type": "record",
              "fields": [
                {
                  "name": "maximum",
                  "type": "int"
                },
                {
                  "name": "minimum",
                  "type": "int"
                }
              ]
            }
          },
          {
            "name": "education",
            "type": "string"
          },
          {
            "name": "contract",
            "type": "string"
          },
          {
            "name": "benefits",
            "type": {
              "name": "benefits_def",
              "namespace": "levee.datalake.body.benefits",
              "doc": "",
              "type": "record",
              "fields": [
                {
                  "name": "transit_voucher",
                  "type": "boolean"
                },
                {
                  "name": "meal_ticket",
                  "type": "boolean"
                },
                {
                  "name": "food_stamps",
                  "type": "boolean"
                },
                {
                  "name": "grocery",
                  "type": "boolean"
                },
                {
                  "name": "on_site_meal",
                  "type": "boolean"
                },
                {
                  "name": "life_insurance",
                  "type": "boolean"
                },
                {
                  "name": "healthcare_plan",
                  "type": "boolean"
                },
                {
                  "name": "dental_plan",
                  "type": "boolean"
                },
                {
                  "name": "others",
                  "type": "boolean"
                },
                {
                  "name": "career_plan",
                  "type": "boolean"
                },
                {
                  "name": "training",
                  "type": "boolean"
                }
              ]
            }
          },
          {
            "name": "address",
            "type": {
              "name": "address_def",
              "namespace": "levee.datalake.body.address",
              "doc": "",
              "type": "record",
              "fields": [
                {
                  "name": "id",
                  "type": "int"
                },
                {
                  "name": "zip_code",
                  "type": "string"
                },
                {
                  "name": "name",
                  "type": "null"
                },
                {
                  "name": "address",
                  "type": "string"
                },
                {
                  "name": "number",
                  "type": "string"
                },
                {
                  "name": "complement",
                  "type": "string"
                },
                {
                  "name": "suburb",
                  "type": "string"
                },
                {
                  "name": "city",
                  "type": "string"
                },
                {
                  "name": "state",
                  "type": "string"
                },
                {
                  "name": "company_id",
                  "type": "int"
                },
                {
                  "name": "coordinates",
                  "type": {
                    "name": "coordinates_def",
                    "namespace": "levee.datalake.body.address.coordinates",
                    "doc": "",
                    "type": "record",
                    "fields": [
                      {
                        "name": "latitude",
                        "type": "float"
                      },
                      {
                        "name": "longitude",
                        "type": "float"
                      }
                    ]
                  }
                },
                {
                  "name": "reference",
                  "type": "string"
                },
                {
                  "name": "created_at",
                  "type": "string"
                },
                {
                  "name": "updated_at",
                  "type": "string"
                }
              ]
            }
          },
          {
            "name": "updated_at",
            "type": "string"
          },
          {
            "name": "created_at",
            "type": "string"
          },
          {
            "name": "origin",
            "type": "string"
          },
          {
            "name": "company",
            "type": {
              "name": "company_def",
              "namespace": "levee.datalake.body.company",
              "doc": "",
              "type": "record",
              "fields": [
                {
                  "name": "id",
                  "type": "int"
                },
                {
                  "name": "name",
                  "type": "string"
                }
              ]
            }
          },
          {
            "name": "open_positions",
            "type": "int"
          },
          {
            "name": "allow_cv_db",
            "type": "boolean"
          },
          {
            "name": "allow_el_db",
            "type": "boolean"
          },
          {
            "name": "approved_count",
            "type": "null"
          },
          {
            "name": "hired_count",
            "type": "null"
          },
          {
            "name": "show_up_count",
            "type": "null"
          },
          {
            "name": "knowledge_test",
            "type": "null"
          },
          {
            "name": "max_distance",
            "type": "float"
          },
          {
            "name": "interview_place",
            "type": {
              "name": "interview_place_def",
              "namespace": "levee.datalake.body.interview_place",
              "doc": "",
              "type": "record",
              "fields": [
                {
                  "name": "id",
                  "type": "int"
                },
                {
                  "name": "job_id",
                  "type": "int"
                },
                {
                  "name": "contact",
                  "type": "string"
                },
                {
                  "name": "address",
                  "type": {
                    "name": "address_def",
                    "namespace": "levee.datalake.body.interview_place.address",
                    "doc": "",
                    "type": "record",
                    "fields": [
                      {
                        "name": "id",
                        "type": "int"
                      },
                      {
                        "name": "zip_code",
                        "type": "string"
                      },
                      {
                        "name": "name",
                        "type": "null"
                      },
                      {
                        "name": "address",
                        "type": "string"
                      },
                      {
                        "name": "number",
                        "type": "string"
                      },
                      {
                        "name": "complement",
                        "type": "string"
                      },
                      {
                        "name": "suburb",
                        "type": "string"
                      },
                      {
                        "name": "city",
                        "type": "string"
                      },
                      {
                        "name": "state",
                        "type": "string"
                      },
                      {
                        "name": "company_id",
                        "type": "int"
                      },
                      {
                        "name": "coordinates",
                        "type": {
                          "name": "coordinates_def",
                          "namespace": "levee.datalake.body.interview_place.address.coordinates",
                          "doc": "",
                          "type": "record",
                          "fields": [
                            {
                              "name": "latitude",
                              "type": "float"
                            },
                            {
                              "name": "longitude",
                              "type": "float"
                            }
                          ]
                        }
                      },
                      {
                        "name": "reference",
                        "type": "string"
                      },
                      {
                        "name": "created_at",
                        "type": "string"
                      },
                      {
                        "name": "updated_at",
                        "type": "string"
                      }
                    ]
                  }
                }
              ]
            }
          },
          {
            "name": "salary",
            "type": {
              "name": "salary_def",
              "namespace": "levee.datalake.body.salary",
              "doc": "",
              "type": "record",
              "fields": [
                {
                  "name": "id",
                  "type": "int"
                },
                {
                  "name": "kind",
                  "type": "string"
                },
                {
                  "name": "minimum",
                  "type": "null"
                },
                {
                  "name": "maximum",
                  "type": "null"
                },
                {
                  "name": "value",
                  "type": "null"
                },
                {
                  "name": "additional",
                  "type": "null"
                }
              ]
            }
          },
          {
            "name": "period",
            "type": {
              "name": "period_def",
              "namespace": "levee.datalake.body.period",
              "doc": "",
              "type": "record",
              "fields": [
                {
                  "name": "id",
                  "type": "int"
                },
                {
                  "name": "kind",
                  "type": "string"
                },
                {
                  "name": "start_day",
                  "type": "string"
                },
                {
                  "name": "finish_day",
                  "type": "string"
                },
                {
                  "name": "ratio",
                  "type": "null"
                }
              ]
            }
          },
          {
            "name": "working_times",
            "type": {
              "type": "array",
              "items": {
                "name": "working_times",
                "namespace": "levee.datalake.body.working_times.working_times",
                "doc": "",
                "type": "record",
                "fields": [
                  {
                    "name": "id",
                    "type": "int"
                  },
                  {
                    "name": "job_id",
                    "type": "int"
                  },
                  {
                    "name": "start_hour",
                    "type": "string"
                  },
                  {
                    "name": "finish_hour",
                    "type": "string"
                  }
                ]
              }
            }
          },
          {
            "name": "state_changes",
            "type": {
              "type": "array",
              "items": {
                "name": "state_changes",
                "namespace": "levee.datalake.body.state_changes.state_changes",
                "doc": "",
                "type": "record",
                "fields": [
                  {
                    "name": "id",
                    "type": "int"
                  },
                  {
                    "name": "old_state",
                    "type": "string"
                  },
                  {
                    "name": "new_state",
                    "type": "string"
                  },
                  {
                    "name": "updated_by",
                    "type": {
                      "name": "updated_by_def",
                      "namespace": "levee.datalake.body.state_changes.state_changes.updated_by",
                      "doc": "",
                      "type": "record",
                      "fields": [
                        {
                          "name": "id",
                          "type": "int"
                        },
                        {
                          "name": "rank",
                          "type": "null"
                        },
                        {
                          "name": "branch_id",
                          "type": "null"
                        },
                        {
                          "name": "role_type",
                          "type": "string"
                        },
                        {
                          "name": "company_id",
                          "type": "null"
                        }
                      ]
                    }
                  },
                  {
                    "name": "job_id",
                    "type": "int"
                  },
                  {
                    "name": "created_at",
                    "type": "string"
                  },
                  {
                    "name": "updated_at",
                    "type": "string"
                  }
                ]
              }
            }
          },
          {
            "name": "interviews",
            "type": {
              "type": "array",
              "items": {
                "name": "interviews",
                "namespace": "levee.datalake.body.interviews.interviews",
                "doc": "",
                "type": "record",
                "fields": [
                  {
                    "name": "id",
                    "type": "int"
                  },
                  {
                    "name": "interview_place_id",
                    "type": "int"
                  },
                  {
                    "name": "date",
                    "type": "string"
                  },
                  {
                    "name": "candidates",
                    "type": "int"
                  },
                  {
                    "name": "max_candidates",
                    "type": "int"
                  }
                ]
              }
            }
          }
        ]
      }
    }
  ]
}
```

Data
```
{
  "headers": {
    "appName": "JobsSVC",
    "resource": "job",
    "origin": "el",
    "action": "activated",
    "schemaVersion": 1.0
  },
  "body": {
    "id": 32045,
    "title": "Putzideiro",
    "alternative_name": "",
    "category": 210,
    "position": 206,
    "experience": 0,
    "drivers_license": [],
    "description": "adasdasdd",
    "short_description": "asddadasasd",
    "available_at": null,
    "close_at": null,
    "created_by": {
      "id": 4519253,
      "rank": "admin",
      "branch_id": null,
      "recruiter": true,
      "role_type": "RECRUITER",
      "user_name": "Bruno Boni",
      "company_id": 5151
    },
    "state": "activated",
    "company_id": 5151,
    "company_name": "Leveeeeees",
    "branch_id": 5210,
    "candidates": 0,
    "candidates_requested": 123,
    "schedule_type": "auto",
    "gender": "both",
    "age": {
      "maximum": 60,
      "minimum": 16
    },
    "education": "any",
    "contract": "regular",
    "benefits": {
      "transit_voucher": true,
      "meal_ticket": false,
      "food_stamps": false,
      "grocery": true,
      "on_site_meal": true,
      "life_insurance": false,
      "healthcare_plan": false,
      "dental_plan": false,
      "others": false,
      "career_plan": false,
      "training": false
    },
    "address": {
      "id": 63803,
      "zip_code": "02054-050",
      "name": null,
      "address": "Rua Henrique Felipe da Costa",
      "number": "123",
      "complement": "asdasdas",
      "suburb": "Vila Guilherme",
      "city": "São Paulo",
      "state": "SP",
      "company_id": 5151,
      "coordinates": {
        "latitude": -23.51788,
        "longitude": -46.6075495
      },
      "reference": "asdasdas",
      "created_at": "2018-06-14T17:17:48+00:00",
      "updated_at": "2018-06-14T17:17:48+00:00"
    },
    "updated_at": "2018-06-14T17:18:38+00:00",
    "created_at": "2018-06-14T17:17:48+00:00",
    "origin": "EL",
    "company": {
      "id": 5151,
      "name": "Leveeeeees"
    },
    "open_positions": 123,
    "allow_cv_db": true,
    "allow_el_db": true,
    "approved_count": null,
    "hired_count": null,
    "show_up_count": null,
    "knowledge_test": null,
    "max_distance": 15.0,
    "interview_place": {
      "id": 31770,
      "job_id": 32045,
      "contact": "asdasdasasdw",
      "address": {
        "id": 63804,
        "zip_code": "02054-050",
        "name": null,
        "address": "Rua Henrique Felipe da Costa",
        "number": "123",
        "complement": "asdasdas",
        "suburb": "Vila Guilherme",
        "city": "São Paulo",
        "state": "SP",
        "company_id": 5151,
        "coordinates": {
          "latitude": -23.51788,
          "longitude": -46.6075495
        },
        "reference": "asdasdas",
        "created_at": "2018-06-14T17:17:48+00:00",
        "updated_at": "2018-06-14T17:17:48+00:00"
      }
    },
    "salary": {
      "id": 32044,
      "kind": "negotiable",
      "minimum": null,
      "maximum": null,
      "value": null,
      "additional": null
    },
    "period": {
      "id": 32045,
      "kind": "fixed",
      "start_day": "sunday",
      "finish_day": "saturday",
      "ratio": null
    },
    "working_times": [
      {
        "id": 64473,
        "job_id": 32045,
        "start_hour": "00:00",
        "finish_hour": "04:30"
      }
    ],
    "state_changes": [
      {
        "id": 1722,
        "old_state": "draft",
        "new_state": "activated",
        "updated_by": {
          "id": 48,
          "rank": null,
          "branch_id": null,
          "role_type": "SUPPORT",
          "company_id": null
        },
        "job_id": 32045,
        "created_at": "2018-06-14T17:18:38+00:00",
        "updated_at": "2018-06-14T17:18:38+00:00"
      }
    ],
    "interviews": [
      {
        "id": 249503,
        "interview_place_id": 31770,
        "date": "2018-06-28T23:12:00+00:00",
        "candidates": 0,
        "max_candidates": 123
      }
    ]
  }
}
```

**Comment by scottbelden** [comment]
When you call `writer` are you giving it just the data dictionary? The documentation should probably be a bit more clear (and maybe there's a way to add some check to the incoming data), but the `records` argument should be an iterable of data dictionaries (typically this is something like a list, but it should be able to be a tuple or a generator or something else like that).

As a side note, debugging can be a little awkward because of the layout of this library. There is both a cython implementation and a pure python implementation. When running under the PyPy interpreter, the pure python is used (so the files like `_write_py.py` whereas on the CPython interpreter the cython version is used (files like `_write.pyx`). If you wanted to debug, the easiest way would probably be to go to the fastavro install folder and remove the compiled cython files (either `.so`, `.pyd`, or maybe something else). This will force it to use the pure python (and your stack trace should change from having `_write.pyx` to `_write_py.py`) and then you would be able to use `pdb`

**Comment by IceS2** [comment]
Thanks Scott! You've ben awesome lifting all the small rocks I found in my way. It's not that explicit, but now I see the example uses a list of records...
And thanks for telling me how to debug fastavro (=

**Comment by prasannav2** [comment]
@scottbelden @IceS2 I am facing the same issue. I am also dealing with Highly complicated nested json data. It would be really helpful if you can provide me with the exact steps that you followed to get over this roadblock. Please let me know.

**Comment by scottbelden** [comment]
If the problem is some bad data, usually using the [validate functions](https://fastavro.readthedocs.io/en/latest/validation.html) is a good way of figuring out where the problem is. Let me know if you have a chance to try one of those and whether or not it helps.

**Comment by prasannav2** [comment]
The validation passes. I simplified the data to get to the root of the issue. The value schema and the json file are an exact match.

my value schema is like:

{
  "type" : "record",
  "name" : "MyClass",
  "namespace" : "com.test.avro",
  "fields" : [ {
    "name" : "familyid",
    "type" : "string"
  }, {
    "name" : "hh_control_status_indicators",
    "type" : "long"
  }, {
    "name" : "lifestyle_models",
    "type" : {
      "type" : "record",
      "name" : "lifestyle_models",
      "fields" : [ {
        "name" : "lhi_high_ticket",
        "type" : "string"
      }, {
        "name" : "lhi_stamps_coins",
        "type" : "string"
      }, {
        "name" : "lhi_stocks_bonds",
        "type" : "string"
      }, {
        "name" : "lhi_foreign_travel",
        "type" : "string"
      } ]
    }
  } ]
}

And my json input data is like.

{"familyid": "502363543381", "hh_control_status_indicators": 1, "lifestyle_models": {"lhi_high_ticket": "0", "lhi_stamps_coins": "0", "lhi_stocks_bonds": "0", "lhi_foreign_travel": "0"}}

Now my program is:


from time import sleep
import json
import uuid
from confluent_kafka import avro
from confluent_kafka.avro import AvroProducer

value_schema = avro.load("C:/Users/Dell/Kafka/confluent-kafka-python/dev4/valueschema.avsc")
key_schema = avro.load("C:/Users/Dell/Kafka/confluent-kafka-python/dev4/keyschema.avsc")

value = {"name":"value", "familyid":'value', "hh_control_status_indicators": 99999,
         "lifestyle_models": {"lhi_high_ticket": "0", "lhi_stamps_coins": "0", "lhi_stocks_bonds": "0", "lhi_foreign_travel": "0"}}

key = {"name": 'Key'}

avroProducer = AvroProducer(
    {'bootstrap.servers': 'localhost:9092',
     'schema.registry.url': "http://localhost:8081"}, default_key_schema=key_schema, default_value_schema=value_schema)
avroProducer.produce(topic='test-topic1', value=value,key=key, key_schema=key_schema, value_schema=value_schema)

fObj = open("C:/Users/Dell/Kafka/confluent-kafka-python/dev4/NE01_ODBX49_202109.sample1.json", 'r')
obj = json.load(fObj)
print(type(obj))
for i in obj:
  value = i

  avroProducer.produce(topic='test-topic1', value=value,key=key, key_schema=key_schema, value_schema=value_schema)
  sleep(1)
  print(value)
  avroProducer.flush()


When I run this program, I get the following error message. 

Traceback (most recent call last):
  File "c:\Users\Dell\Kafka\confluent-kafka-python\dev4\avro_producer_USETHIS1.py", line 27, in <module>
    avroProducer.produce(topic='test-topic1', value=value,key=key, key_schema=key_schema, value_schema=value_schema)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\confluent_kafka\avro\__init__.py", line 99, in produce
    value = self._serializer.encode_record_with_schema(topic, value_schema, value)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\confluent_kafka\avro\serializer\message_serializer.py", line 119, in encode_record_with_schema
    return self.encode_record_with_schema_id(schema_id, record, is_key=is_key)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\confluent_kafka\avro\serializer\message_serializer.py", line 153, in encode_record_with_schema_id
    writer(record, outf)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\confluent_kafka\avro\serializer\message_serializer.py", line 84, in <lambda>
    return lambda record, fp: schemaless_writer(fp, parsed_schema, record)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\fastavro\_write_py.py", line 690, in schemaless_writer
    write_data(encoder, record, schema, named_schemas, "")
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\fastavro\_write_py.py", line 285, in write_data
    return fn(encoder, datum, schema, named_schemas, fname)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python36\lib\site-packages\fastavro\_write_py.py", line 233, in write_record
    datum.get(name, field.get("default")),
AttributeError: 'str' object has no attribute 'get'
%4|1648844026.982|TERMINATE|rdkafka#producer-1| [thrd:app]: Producer terminating with 1 message (22 bytes) still in queue or transit: use flush() to wait for outstanding message delivery


![image](https://user-images.githubusercontent.com/96099411/161335111-e5694d99-937f-4940-9675-2589800e73b6.png)


It would be really helpful if you could help me debug this as I am stuck on this issue for days.
