### ISSUE TITLE
Cannot read dec.avro from 

### ISSUE THREAD

**Issue by jkolash** [fastavro/fastavro#261]
For the following code
```python
import fastavro

with open("dec.avro", "rb") as fo:
     for record in fastavro.reader(fo):
         print(record)
```
I get this error

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    for record in fastavro.reader(fo):
  File "fastavro/_read.pyx", line 622, in _iter_avro_blocks
  File "fastavro/_read.pyx", line 641, in __iter__
  File "fastavro/_read.pyx", line 539, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 451, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 552, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 172, in fastavro._read.read_bytes_decimal
  File "fastavro/_read.pyx", line 174, in fastavro._read.read_bytes_decimal
  File "fastavro/_read.pyx", line 207, in fastavro._read._read_decimal
  File "fastavro/_read.pyx", line 208, in fastavro._read._read_decimal
TypeError: an integer is required
```

dec.avro is from
https://issues.apache.org/jira/browse/HIVE-5823

environment + version information
```bash
(env)  env python --version
Python 3.6.4
(env)  env pip freeze
fastavro==0.21.4
(env)  env
```

**Comment by scottbelden** [comment]
The schema in that avro file has the `precision` of the logicalType set to `"5"` (a string) rather than `5` (an integer). The specification says that the `precision` must be a JSON integer: https://avro.apache.org/docs/1.8.2/spec.html#Decimal

**Comment by scottbelden** [comment]
We should probably do a better job of indicating that problem though, so I'll make an issue for that.
