### ISSUE TITLE
KeyError on nested records

### ISSUE THREAD

**Issue by m0nhawk** [fastavro/fastavro#288]
I have the following IDL schema:

```
protocol PFB {
  record UUID {
    string id;
  }
  record foo {
    UUID id = {"id": ""};
    string description;
    float size;
  }
  record bar {
    UUID id = {"id": ""};
    string name;
    long age;
  }
  record u {
    union{foo, bar} item;
  }
}
```

And the following code to write Avro file:

```
import json

from fastavro import writer, parse_schema, reader


if __name__ == '__main__':
    schema = open("schema/u.avsc", "rb").read()
    schema = json.loads(schema)
    parsed_schema = parse_schema(schema)

    records = [{'item': ('foo', {'description': 'test', 'size': 1.34})},
               {'item': ('bar', {'id': {'id': '#1'}, 'name': 'foobar', 'age': 12})}]

    with open('test.avro', 'wb') as out:
        writer(out, parsed_schema, records)

    with open('test.avro', 'rb') as fo:
        avro_reader = reader(fo)
        for record in avro_reader:
            print(record)
```

The output is expected:

```
{'item': {'id': {'id': ''}, 'description': 'test', 'size': 1.340000033378601}}
{'item': {'id': {'id': '#1'}, 'name': 'foobar', 'age': 12}}
```

Now, when I try to read from other file:

```
from fastavro import reader

if __name__ == '__main__':
    with open('test.avro', 'rb') as fo:
        avro_reader = reader(fo)
        for record in avro_reader:
            print(record)
```

It fails:

```
{'item': {'id': {'id': ''}, 'description': 'test', 'size': 1.340000033378601}}
Traceback (most recent call last):
  File "read.py", line 13, in <module>
    for record in avro_reader:
  File "fastavro/_read.pyx", line 622, in _iter_avro_blocks
  File "fastavro/_read.pyx", line 641, in __iter__
  File "fastavro/_read.pyx", line 539, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 451, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 537, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 426, in fastavro._read.read_union
  File "fastavro/_read.pyx", line 539, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 451, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 543, in fastavro._read._read_data
KeyError: 'UUID'
```

I assume it has something with nested `UUID` record.

Probably it's a bug in `fastavro`, because `avro-tools` reads the file properly. Or it just tolerate the error?

**Comment by scottbelden** [comment]
Could you post the contents of your `schema/u.avsc`?

**Comment by m0nhawk** [comment]
I'm using `avro-tools idl2schemata schema.advl schema` for generation.

```
{
  "type" : "record",
  "name" : "u",
  "fields" : [ {
    "name" : "item",
    "type" : [ {
      "type" : "record",
      "name" : "foo",
      "fields" : [ {
        "name" : "id",
        "type" : {
          "type" : "record",
          "name" : "UUID",
          "fields" : [ {
            "name" : "id",
            "type" : "string"
          } ]
        },
        "default" : {
          "id" : ""
        }
      }, {
        "name" : "description",
        "type" : "string"
      }, {
        "name" : "size",
        "type" : "float"
      } ]
    }, {
      "type" : "record",
      "name" : "bar",
      "fields" : [ {
        "name" : "id",
        "type" : "UUID",
        "default" : {
          "id" : ""
        }
      }, {
        "name" : "name",
        "type" : "string"
      }, {
        "name" : "age",
        "type" : "long"
      } ]
    } ]
  } ]
}
```
