### ISSUE TITLE
Order of values in map makes difference

### ISSUE THREAD

**Issue by Artimi** [fastavro/fastavro#303]
Hi, I have `fastavro==0.21.13` and following script adapted from documentation:
```
from fastavro import writer, reader, parse_schema

schema = {
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields': [
        {'name': 'metadata', 'type': {'type': 'map', 'values': [
	        {'type': 'array', 'items': 'string'}, # array before map
                {'type': 'map', 'values': ['string']},
            ]}},
    ],
}
parsed_schema = parse_schema(schema)

# 'records' can be an iterable (including generator)
records = [
	{'metadata': {'map1': {'map2': 'str'}}}
]

# Writing
with open('weather.avro', 'wb') as out:
    writer(out, parsed_schema, records)

# Reading
with open('weather.avro', 'rb') as fo:
    for record in reader(fo):
        print(record)

```
When I run this I get following error:
```
Traceback (most recent call last):
  File "avro_nested_map.py", line 24, in <module>
    writer(out, parsed_schema, records)
  File "fastavro/_write.pyx", line 724, in fastavro._write.writer
  File "fastavro/_write.pyx", line 689, in fastavro._write.Writer.write
  File "fastavro/_write.pyx", line 537, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 474, in fastavro._write.write_record
  File "fastavro/_write.pyx", line 533, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 395, in fastavro._write.write_map
  File "fastavro/_write.pyx", line 535, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 443, in fastavro._write.write_union
  File "fastavro/_write.pyx", line 531, in fastavro._write.write_data
TypeError: Expected list, got dict
```
However, when I change just order of `values` in first map:
```
schema = {
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields': [
        {'name': 'metadata', 'type': {'type': 'map', 'values': [
                {'type': 'map', 'values': ['string']}, # map before array
	        {'type': 'array', 'items': 'string'},
            ]}},
    ],
}
```
Everything works as expected with output:
```
{'metadata': {'map1': {'map2': 'str'}}}
```
So there is problem with first form that badly recognizes the type. And it is also weird that it works otherwise around.
Is there maybe some problem with the schema? Am I using it right?

**Comment by scottbelden** [comment]
@Artimi Thanks for the report. https://github.com/fastavro/fastavro/pull/304 should resolve this. The validation was allowing any `Iterable` (except strings) to validate as an array which is a problem because dictionaries are iterables. I've updated it to only allow `Sequences`
