### ISSUE TITLE
validate record aggregate error

### ISSUE THREAD

**Issue by corentinghigny** [fastavro/fastavro#350]
More a feature than a bug, but it would be great to receive an error for every erronated field.
In the following example : 
```
>>> import fastavro
>>> schema = {'name': '_', 'type': 'record', 'fields': [{'name': 'a', 'type': 'int'},{'name':'b', 'type':'int'}]}
>>> data = {'a':'foo', 'b': 'bar'}
>>> fastavro.validate(data, schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fastavro/_validation.pyx", line 163, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 206, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 126, in fastavro._validation.validate_record
  File "fastavro/_validation.pyx", line 217, in fastavro._validation.validate
fastavro._validate_common.ValidationError: [
  "_.a is <foo> of type <class 'str'> expected int"
]
```

It would be nice to have an option to receive :
```
fastavro._validate_common.ValidationError: [
  "_.a is <foo> of type <class 'str'> expected int"
  "_.b is <foo> of type <class 'str'> expected int"
]
```
instead.

**Comment by scottbelden** [comment]
This does seem useful and I don't think it would be too hard to add in. In `validate_union` we currently have some logic to append errors to a list and then at the end raise an exception with all of those errors. We would just need to do a similar approach with `validate_record` (and `validate_map` and `validate_array` if we want to be thorough... but those are probably less important).

**Comment by scottbelden** [comment]
Related to https://github.com/fastavro/fastavro/issues/596
