### ISSUE TITLE
No recursive schema resolution for arrays?

### ISSUE THREAD

**Issue by smalyshev** [fastavro/fastavro#363]
I am trying to use schema resolution with fastavro, and it works on simple examples when adding a field, but stops working if a field is added in nested structure.

Consider this schema:
```
{
	"type": "record",
	"name": "DataRecord",
	"fields": [
		{
			"name": "s1",
			"type": "string"
		},
		{
			"name": "subrecord",
			"type": {
				"type": "array",
				"items": {
					"type": "record",
					"name": "SubRecord",
					"fields": [
						{
							"name": "s2",
							"type": "string"
}]}}}]}
```

It has a record which contains an array of subrecords each having one field. I am using it as writer schema. Now I have this reader schema:

```
{
	"type": "record",
	"name": "DataRecord",
	"fields": [
		{
			"name": "s1",
			"type": "string"
		},
		{
			"name": "subrecord",
			"type": {
				"type": "array",
				"items": {
					"name": "SubRecord",
					"type": "record",
					"fields": [
						{
							"name": "s2",
							"type": "string"
						},
						{
							"name": "logs",
							"default": null,
							"type": [
								"null",
								{
									"type": "array",
									"items": {
										"name": "log",
										"type": "record",
										"fields": [
											{
												"name": "msg",
												"type": "string",
												"default": ""
}]}}]}]}}}]}
```

This adds optional logs record which should be no problem for schema resolution - old schema did not have this, so just add default null and everything is OK. However, this does not work. Test script:

```
from io import BytesIO
import json
from fastavro.write import schemaless_writer
from fastavro.read import  schemaless_reader

schema1 = json.loads(open("1.json", 'r').read())
schema2 = json.loads(open("2.json", 'r').read())

data = {
        's1': "test",
        'subrecord': []
}

binary1 = BytesIO()
schemaless_writer(binary1, schema1, data)
with open('f', 'wb') as f:
    f.write(binary1.getvalue())
    
binary1.seek(0)
print(schemaless_reader(binary1, schema1))

binary1.seek(0)
print(schemaless_reader(binary1, schema1, reader_schema=schema2))
```
produces this:
```
{'s1': 'test', 'subrecord': []}
Traceback (most recent call last):
  File "tf.py", line 23, in <module>
    print(schemaless_reader(binary1, schema1, reader_schema=schema2))
  File "fastavro/_read.pyx", line 759, in fastavro._read.schemaless_reader
  File "fastavro/_read.pyx", line 769, in fastavro._read.schemaless_reader
  File "fastavro/_read.pyx", line 536, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 447, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 508, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 119, in fastavro._read.match_schemas
fastavro._read_common.SchemaResolutionError: Schema mismatch: {'type': 'array', 'items': {'type': 'record', 'name': 'SubRecord', 'fields': [{'name': 's2', 'type': 'string'}]}} is not {'type': 'array', 'items': {'type': 'record', 'name': 'SubRecord', 'fields': [{'name': 's2', 'type': 'string'}, {'default': None, 'name': 'logs', 'type': ['null', {'type': 'array', 'items': {'type': 'record', 'name': 'log', 'fields': [{'default': '', 'name': 'msg', 'type': 'string'}]}}]}]}}
```

This seems to be because match_schemas when checking array items uses:
```
      elif w_type == r_type == 'array':
            if match_types(w_schema['items'], r_schema['items']):
                return True
 ```
 which tries to compare records directly instead of checking that those both are records and comparing them later. It happens on the top level but not when checking arrays and maps.

**Comment by scottbelden** [comment]
Thanks for the detailed report. I think I have a solution [here](https://github.com/fastavro/fastavro/pull/364).
