### ISSUE TITLE
how to buffering records to avro file by chunks?

### ISSUE THREAD

**Issue by regaladodiaz** [fastavro/fastavro#382]
I wondered if there is a way to write an avro file by chunks to a buffer.
I'm trying to do this
```python
import fastavro
import io
import os

schema = {
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields': [
        {'name': 'a', 'type': 'int'},
        {'name': 'b', 'type': 'int'}]
    }

# generate records
def generate_records():
    odd = [x for x in range(1,1000) if x % 2 !=0]
    even = [x for x in range(1,1000) if x % 2 ==0]
    records = [{'a': x, 'b': y} for x,y in zip(odd, even)]
    return records

def write_avro_streaming(records, chunk_size, file_name): 
    parsed_schema = fastavro.parse_schema(schema)
    with open(file_name, 'wb') as fp:
        with io.BytesIO() as bytes_writer:
            while records:
                if len(records)>= chunk_size:
                    partial_results = records[:chunk_size]
                    records = records[chunk_size:]
                else:
                    partial_results = records
                    records = []

                fastavro.writer(bytes_writer, parsed_schema, partial_results)
                raw_bytes = bytes_writer.getvalue()
                fp.write(raw_bytes)


if __name__ == '__main__':
    records = generate_records()
    file_name = 'fp.avro'
    write_avro_streaming(records[:100], 10, file_name)

```
but when I run `python buffered_avro.py && fastavro fp.avro` I got `ValueError: expected sync marker not found`
 
```bash
$python buffered_avro.py && fastavro fp.avro
{"a": 1, "b": 2}
{"a": 3, "b": 4}
{"a": 5, "b": 6}
{"a": 7, "b": 8}
{"a": 9, "b": 10}
{"a": 11, "b": 12}
{"a": 13, "b": 14}
{"a": 15, "b": 16}
{"a": 17, "b": 18}
{"a": 19, "b": 20}
Traceback (most recent call last):
  File "/Users/developer/.virtualenvs/platform-management/bin/fastavro", line 10, in <module>
    sys.exit(main())
  File "/Users/developer/.virtualenvs/platform-management/lib/python3.7/site-packages/fastavro/__main__.py", line 81, in main
    for record in reader:
  File "fastavro/_read.pyx", line 639, in _iter_avro_records
  File "fastavro/_read.pyx", line 564, in fastavro._read.skip_sync
ValueError: expected sync marker not found
```

**Comment by scottbelden** [comment]
There are two ways you can do this currently.

The first is to write the first chunk to the file and then append the other times. Here's how you would modify `write_avro_streaming`:

```python
def write_avro_streaming(records, chunk_size, file_name):
    parsed_schema = fastavro.parse_schema(schema)

    some_records_written = False
    while records:
        if len(records)>= chunk_size:
            partial_results = records[:chunk_size]
            records = records[chunk_size:]
        else:
            partial_results = records
            records = []

        if some_records_written is True:
            with open(file_name, 'a+b') as fp:
                fastavro.writer(fp, parsed_schema, partial_results)
        else:
            with open(file_name, 'wb') as fp:
                fastavro.writer(fp, parsed_schema, partial_results)
            some_records_written = True
```

It's necessary to change the file mode when appending.


The other way is to use the `fastavro.write.Writer` interface that isn't documented much or at all because it's a bit lower level than most people need. To use that, it would look like this:

```python
def write_avro_streaming(records, chunk_size, file_name):
    parsed_schema = fastavro.parse_schema(schema)
    with open(file_name, 'wb') as fp:
        writer = fastavro.write.Writer(fp, parsed_schema)
        while records:
            if len(records)>= chunk_size:
                partial_results = records[:chunk_size]
                records = records[chunk_size:]
            else:
                partial_results = records
                records = []

            for record in partial_results:
                writer.write(record)
        writer.flush()
```

Do either of those help?

**Comment by regaladodiaz** [comment]
The second way works like a charm!, thanks @scottbelden

**Comment by rkarthik29** [comment]
@scottbelden will this create blocks in the output file? I am trying to ensure that a file i am processing when comings has two blocks. I want to ensure there are two blocks in the outgoing file. is that doable?
