### ISSUE TITLE
fastavro._read.read_bytes: ValueError: read length must be non-negative or -1 

### ISSUE THREAD

**Issue by osvalban** [fastavro/fastavro#390]
Hello.

I am using a Google Cloud Dataflow [template](https://cloud.google.com/dataflow/docs/guides/templates/provided-batch#avrofiletocloudbigtable) [[source code]](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/main/java/com/google/cloud/teleport/bigtable/AvroToBigtable.java) to read avro files in GCS and write to a BigTable instance. 

The Dataflow job runs to about 94% completion, and then craps out with the following exception:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dataflow_worker/batchworker.py", line 650, in do_work
    work_executor.execute()
  File "/usr/local/lib/python3.7/site-packages/dataflow_worker/executor.py", line 176, in execute
    op.start()
  File "dataflow_worker/native_operations.py", line 38, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 39, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 44, in dataflow_worker.native_operations.NativeReadOperation.start
  File "dataflow_worker/native_operations.py", line 48, in dataflow_worker.native_operations.NativeReadOperation.start
  File "/usr/local/lib/python3.7/site-packages/apache_beam/io/concat_source.py", line 86, in read
    range_tracker.sub_range_tracker(source_ix)):
  File "/usr/local/lib/python3.7/site-packages/apache_beam/io/avroio.py", line 469, in read_records
    blocks = block_reader(f)
  File "fastavro/_read.pyx", line 756, in fastavro._read.block_reader.__init__
  File "fastavro/_read.pyx", line 700, in fastavro._read.file_reader.__init__
  File "fastavro/_read.pyx", line 564, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 460, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 560, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 407, in fastavro._read.read_map
  File "fastavro/_read.pyx", line 311, in fastavro._read.read_utf8
  File "fastavro/_read.pyx", line 304, in fastavro._read.read_bytes
ValueError: read length must be non-negative or -1`

I need some help understanding what can cause this exception and any pointers on how it may be fixed.

**Comment by scottbelden** [comment]
The exception appears to happen while trying to read the header of the file but the header seems to be malformed. For example, I can replicate this error by writing a binary file that has just partial header:

```python
import fastavro

with open("test.avro", "wb") as fp: 
    fp.write(b"Obj1\x021")

with open("test.avro", "rb") as fp: 
    fastavro.block_reader(fp)
```

And with that bad file I get a similar error:

```python
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    fastavro.block_reader(fp)
  File "fastavro/_read.pyx", line 756, in fastavro._read.block_reader.__init__
    file_reader.__init__(self, fo, reader_schema)
  File "fastavro/_read.pyx", line 700, in fastavro._read.file_reader.__init__
    self._header = _read_data(self.fo, HEADER_SCHEMA)
  File "fastavro/_read.pyx", line 564, in fastavro._read._read_data
    data = read_record(fo, writer_schema, reader_schema)
  File "fastavro/_read.pyx", line 460, in fastavro._read.read_record
    record[field['name']] = _read_data(fo, field['type'])
  File "fastavro/_read.pyx", line 560, in fastavro._read._read_data
    data = read_map(fo, writer_schema, reader_schema)
  File "fastavro/_read.pyx", line 407, in fastavro._read.read_map
    key = read_utf8(fo)
  File "fastavro/_read.pyx", line 311, in fastavro._read.read_utf8
    return btou(read_bytes(fo), 'utf-8')
  File "fastavro/_read.pyx", line 304, in fastavro._read.read_bytes
    return fo.read(<long>size)
ValueError: read length must be non-negative or -1
```

Do you know how the avro files were created?

**Comment by osvalban** [comment]
thanks for the quick response @scottbelden! 

> Do you know how the avro files were created?
I used Google's [provided template](https://cloud.google.com/dataflow/docs/guides/templates/provided-batch#cloudbigtabletoavrofile) to read from a BigTable instance and write to avro files in GCS.

The template is available in a GCS bucket: [here](gs://dataflow-templates/latest/Cloud_Bigtable_to_GCS_Avro)

From what I can tell, [this](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/main/java/com/google/cloud/teleport/bigtable/BigtableToAvro.java#L135) is the actual source code which maps BigTable rows to avro.

Essentially, I am testing the process of going from Cloud Bigtable to Cloud Storage Avro and vice-versa.

**Comment by scottbelden** [comment]
Is there any way you can provide the actual avro file? I understand of course if that's not possible.

**Comment by osvalban** [comment]
I can't share it unfortunately. Can the exception be handled more gracefully? If not, is there some modification I could make to the default [class](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/src/main/java/com/google/cloud/teleport/bigtable/BigtableToAvro.java) for validation as the avro file is written?

**Comment by scottbelden** [comment]
It's hard to make a suggestion about what would be best to do.

If the file is a valid file but a bug in fastavro is causing the exception then I would want to fix that, but I'm not sure if that's the case. If it's possible to use another avro implementation and see if it fails to read the avro file then that might give a better idea of if the problem is in the file or our implementation.

As for modifying that class, I'm not as proficient in Java and so I'm not sure if there are any modifications that would be beneficial.
