### ISSUE TITLE
Error writing JSON records with schemas that include dependent schemas

### ISSUE THREAD

**Issue by gudjonragnar** [fastavro/fastavro#418]
I have an Avro spec that I want to use when writing records as JSON. This spec contains schemas that have dependencies. When trying to write records using `json_writer` I however faced this:
```
Traceback (most recent call last):
  File "/Users/gudjonragnar/fastavro/tests/test_json.py", line 493, in test_with_dependent_schema
    new_records = roundtrip(schema, records)
  File "/Users/gudjonragnar/fastavro/tests/test_json.py", line 13, in roundtrip
    json_writer(new_file, schema, records)
  File "/Users/gudjonragnar/fastavro/fastavro/json_write.py", line 46, in json_writer
    return writer(AvroJSONEncoder(fo), schema, records)
  File "/Users/gudjonragnar/fastavro/fastavro/_write_py.py", line 595, in writer
    codec_compression_level,
  File "/Users/gudjonragnar/fastavro/fastavro/_write_py.py", line 476, in __init__
    self.encoder.configure(self.schema)
  File "/Users/gudjonragnar/fastavro/fastavro/io/json_encoder.py", line 69, in configure
    self._parser = Parser(schema, self.do_action)
  File "/Users/gudjonragnar/fastavro/fastavro/io/parser.py", line 14, in __init__
    self.stack = self.parse()
  File "/Users/gudjonragnar/fastavro/fastavro/io/parser.py", line 17, in parse
    symbol = self._parse(self.schema)
  File "/Users/gudjonragnar/fastavro/fastavro/io/parser.py", line 31, in _parse
    production.insert(0, self._parse(field["type"]))
  File "/Users/gudjonragnar/fastavro/fastavro/io/parser.py", line 95, in _parse
    raise Exception("Unhandled type: {}".format(record_type))
Exception: Unhandled type: test.Dependency
```
where `test.Dependency` is a schema that is already loaded and is featured in a field in another schema as so:
```
...
    "fields": [{
        "name": "_dependency",
        "type": "Dependency"
    }]
...
```
I wrote a simple test, using the `roundtrip()` method from `test_json.py` which fails with the above error.
```
from fastavro.schema import parse_schema

 def test_with_dependent_schema():
    """Tests a schema with dependent schema"""
    dependency = {
        "type": "record",
        "name": "Dependency",
        "namespace": "test",
        "fields": [{
            "name": "_name",
            "type": "string"
        }]
    }

    schema = {
        "type": "record",
        "name": "Test",
        "namespace": "test",
        "fields": [{
            "name": "_name",
            "type": "string"

        }, {
            "name": "_dependency",
            "type": "Dependency"
        }]
    }

    records = [{
        '_name': 'parent',
        '_dependency': {
            '_name': 'child'
        } 
    }]

    parse_schema(dependency, "/tmp/dir")
    parse_schema(schema, "/tmp/dir")

    new_records = roundtrip(schema, records)
    assert records == new_records
```
I found a simple fix for this which I will submit a PR for. I want to include the test above, would `test_json.py` be a fitting place for it @scottbelden ?

**Comment by scottbelden** [comment]
Resolved via https://github.com/fastavro/fastavro/pull/419
