### ISSUE TITLE
ValueError: {} (type <class 'dict'>) do not match

### ISSUE THREAD

**Issue by JulianScherp** [fastavro/fastavro#440]
I'm trying to write the Metadata of my GDrive files into an Avro file, but there seems to be a problem with "videoMediaMetadata" and "imageMediaMetadata.location".
I don't see the difference to, for example, "permissons".
Any recommedations or ideas how to fix it would be really appreciated.

Instruction how to connect to the GDrive API:
https://developers.google.com/drive/api/v3/quickstart/python

Here are more informations about the Metadata:
https://developers.google.com/drive/api/v3/reference/files

with the following code it should be possible to reproduce the `code:`

```
from __future__ import print_function
from fastavro import writer, parse_schema
import pickle
import os.path
from googleapiclient.discovery import build, Resource
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# If modifying these scopes, delete the file token.pickle.
SCOPES = ['https://www.googleapis.com/auth/drive']

def main(permissions=None):
    """Shows basic usage of the Drive v3 API.
    Prints the names and ids of the first 10 files the user has access to.
    """

    creds = None
    # The file token.pickle stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    service = build('drive', 'v3', credentials=creds)

    # Call the Drive v3 API
    # Import of Metadata
    results = service.files().list(
        pageSize=10, fields="nextPageToken, files("
                            "kind,"
                            " id,"
                            " name,"
                            " mimeType,"
                            " description,"
                            " starred,"
                            " trashed,"
                            " explicitlyTrashed,"
                            " trashingUser,"
                            " trashedTime,"
                            " parents,"
                            " properties"
                            " (key),"
                            " appProperties"
                            " (key),"
                            " spaces,"
                            " teamDriveId,"
                            " driveId,"
                            " lastModifyingUser,"
                            " shared,"
                            " ownedByMe,"
                            " capabilities,"
                            " viewersCanCopyContent,"
                            " copyRequiresWriterPermission,"
                            " writersCanShare,"
                            " permissions,"
                            " permissionIds,"
                            " hasAugmentedPermissions,"
                            " folderColorRgb,"
                            " originalFilename,"
                            " fullFileExtension,"
                            " fileExtension,"
                            " md5Checksum,"
                            " size,"
                            " quotaBytesUsed,"
                            " headRevisionId,"
                            " contentHints, "
                            " imageMediaMetadata,"
                            " videoMediaMetadata,"
                            " isAppAuthorized,"
                            "shortcutDetails "

                            ")"
    ).execute()
    records = results.get('files', [])

    # Writes Avro File
    if not records:
        print('No files found.')
    else:
        print('Files:')
        for edwSequence, record in enumerate(records, start=1):
            print("edwSequence: ", edwSequence, record)

            schema = {
                'name': 'GDrive',
                'type': 'record',
                'fields': [
                    {'name': 'kind', 'type': 'string'},
                    {'name': 'name', 'type': 'string'},
                    {'name': 'id', 'type': 'string'},
                    {'name': 'mimeType', 'type': 'string'},
                    {'name': 'description', 'type': ['string', 'null']},
                    {'name': 'starred', 'type': ['boolean', 'null']},
                    {'name': 'trashed', 'type': ['boolean', 'null']},
                    {'name': 'trashingUser', 'type': ['string', 'null']},
                    {'name': 'trashedTime', 'type': ['string', 'null']},
                    {'name': 'properties', 'type': ['string', 'null']},
                    {'name': 'appProperties', 'type': ['string', 'null']},
                    {'name': 'spaces',
                     'type': {'type': 'array', 'items': 'string'}
                     },
                    {'name': 'driveId', 'type': ['string', 'null']},
                    {"name": "lastModifyingUser",
                     "type": {
                         "type": "record",
                         "name": "lastModifyingUser",
                         "fields": [
                             {"name": "kind", "type": ['string', 'null']},
                             {"name": "displayName", "type": ['string', 'null']},
                             {"name": "photoLink", "type": ['string', 'null']},
                             {"name": "me", "type": ['boolean', 'null']},
                             {"name": "permissionId", "type": ['string', 'null']},
                             {"name": "emailAddress", "type": ['string', 'null']}
                         ]
                     }},
                    {'name': 'shared', 'type': ['boolean', 'null']},
                    {'name': 'ownedByMe', 'type': ['boolean', 'null']},
                    {"name": "capabilities",
                     "type": {
                         "type": "record",
                         "name": "capabilities",
                         "fields": [
                             {"name": "canAddChildren", "type": ['boolean', 'null']},
                             {"name": "canAddMyDriveParent", "type": ['boolean', 'null']},
                             {"name": "canChangeCopyRequiresWriterPermission", "type": ['boolean', 'null']},
                             {"name": "canChangeViewersCanCopyContent", "type": ['boolean', 'null']},
                             {"name": "canComment", "type": ['boolean', 'null']},
                             {"name": "canCopy", "type": ['boolean', 'null']},
                             {"name": "canDelete", "type": ['boolean', 'null']},
                             {"name": "canDeleteChildren", "type": ['boolean', 'null']},
                             {"name": "canDownload", "type": ['boolean', 'null']},
                             {"name": "canEdit", "type": ['boolean', 'null']},
                             {"name": "canListChildren", "type": ['boolean', 'null']},
                             {"name": "canModifyContent", "type": ['boolean', 'null']},
                             {"name": "canMoveChildrenOutOfDrive", "type": ['boolean', 'null']},
                             {"name": "canMoveChildrenWithinDrive", "type": ['boolean', 'null']},
                             {"name": "canMoveItemOutOfDrive", "type": ['boolean', 'null']},
                             {"name": "canMoveItemWithinDrive", "type": ['boolean', 'null']},
                             {"name": "canReadRevisions", "type": ['boolean', 'null']},
                             {"name": "canReadDrive", "type": ['boolean', 'null']},
                             {"name": "canRemoveChildren", "type": ['boolean', 'null']},
                             {"name": "canRemoveMyDriveParent", "type": ['boolean', 'null']},
                             {"name": "canRename", "type": ['boolean', 'null']},
                             {"name": "canShare", "type": ['boolean', 'null']},
                             {"name": "canTrash", "type": ['boolean', 'null']},
                             {"name": "canTrashChildren", "type": ['boolean', 'null']},
                             {"name": "canUntrash", "type": ['boolean', 'null']}
                         ]
                     }},
                    {'name': 'copyRequiresWriterPermission', 'type': ['boolean', 'null']},
                    {'name': 'writersCanShare', 'type': ['boolean', 'null']},
                    {"name": "permissions",
                     "type": {
                         "type": "array",
                         "items": {
                             "type": "record",
                             "name": "permissions",
                             "fields": [
                                 {"name": "kind", "type": ['string', 'null']},
                                 {"name": "id", "type": ['string', 'null']},
                                 {"name": "type", "type": ['string', 'null']},
                                 {"name": "emailAddress", "type": ['string', 'null']},
                                 {"name": "domain", "type": ['string', 'null']},
                                 {"name": "role", "type": ['string', 'null']},
                                 {"name": "allowFileDiscovery", "type": ['boolean', 'null']},
                                 {"name": "displayName", "type": ['string', 'null']},
                                 {"name": "photoLink", "type": ['string', 'null']},
                                 {"name": "expirationTime", "type": ['string', 'null']},
                                 {"name": "permissionDetails",
                                  "type": [{
                                      "type": "record",
                                      "name": "permissionDetails",
                                      "fields": [
                                          {"name": "permissionType", "type": ['string', 'null']},
                                          {"name": "role", "type": ['string', 'null']},
                                          {"name": 'inheritedFrom', "type": ['string', 'null']},
                                          {"name": "inherited", "type": ['boolean', 'null']}
                                      ]

                                  }, "null"]},
                                 {"name": "deleted", "type": ['boolean', 'null']}]
                         }
                     }},
                    {'name': 'permissionIds',
                     'type': {'type': 'array', 'items': 'string'}
                     },
                    {'name': 'hasAugmentedPermissions', 'type': ['boolean', 'null']},
                    {'name': 'folderColorRgb', 'type': ['string', 'null']},
                    {'name': 'originalFilename', 'type': ['string', 'null']},
                    {'name': 'fullFileExtension', 'type': ['string', 'null']},
                    {'name': 'fileExtension', 'type': ['string', 'null']},
                    {'name': 'md5Checksum', 'type': ['string', 'null']},
                    {'name': 'headRevisionId', 'type': ['string', 'null']},
                    {'name': 'thumbnail', 'type': ['string', 'null']},  #
                    {'name': 'image', 'type': ['bytes', 'null']},  #
                    {'name': 'indexableText', 'type': ['string', 'null']},

                    {"name": "imageMediaMetadata",
                     "type": [{
                         "type": "record",
                         "name": "imageMediaMetadata",
                         "fields": [
                             {"name": "width", "type": ['int', 'null']},
                             {"name": "height", "type": ['int', 'null']},
                             {"name": "rotation", "type": ['int', 'null']},
                                                      {"name": "location",
                                                     "type": [{
                                                        "type": "array",
                                                       "items": {
                                                          "type": "record",
                                                         "name": "location",
                                                         "fields": [
                                                           {"name": "latitude", "type": ['double', 'null']},
                                                          {"name": "longtitude", "type": ['double', 'null']},
                                                         {"name": 'altitude', "type": ['double', 'null']}
                                                    ]
                                               }}]
                                          }
                                         ,
                             {'name': 'time', 'type': ['string', 'null']},
                             {'name': 'cameraMake', 'type': ['string', 'null']},
                             {'name': 'cameraModel', 'type': ['string', 'null']},
                             {'name': 'exposureTime', 'type': ['float', 'null']},
                             {'name': 'aperture', 'type': ['float', 'null']},
                             {'name': 'flashUsed', 'type': ['boolean', 'null']},
                             {'name': 'focalLength', 'type': ['float', 'null']},
                             {'name': 'isoSpeed', 'type': ['int', 'null']},
                             {'name': 'meteringMode', 'type': ['string', 'null']},
                             {'name': 'sensor', 'type': ['string', 'null']},
                             {'name': 'exposureMode', 'type': ['string', 'null']},
                             {'name': 'colorSpace', 'type': ['string', 'null']},
                             {'name': 'whiteBalance', 'type': ['string', 'null']},
                             {'name': 'exposureBias', 'type': ['float', 'null']},
                             {'name': 'maxApertureValue', 'type': ['float', 'null']},
                             {'name': 'subjectDistance', 'type': ['int', 'null']},
                             {'name': 'lens', 'type': ['string', 'null']}]
                     }, "null"]},

                    {"name": "videoMediaMetadata",
                     "type": [{
                         "type": "record",
                         "name": "videoMediaMetadata",
                         "fields": [
                             {"name": "width", "type": ['int', 'null']},
                             {"name": "height", "type": ['int', 'null']},
                             {"name": "durationMillis", "type": ['long', 'null']},
                         ]
                     }, "null"]
                     }
                    ,
                    {'name': 'isAppAuthorized', 'type': ['boolean', 'null']},
                    {'name': 'exportLinks', 'type': ['string', 'null']},
                    {'name': 'shortcutDetails', 'type': ['string', 'null']},
                    {'name': 'targetId', 'type': ['string', 'null']},
                    {'name': 'targetMimeType', 'type': ['string', 'null']},

                ],
            }
        parsed_schema = parse_schema(schema)

        for record in records:
            print(u'{0} ({1})'.format(record['name'],
                                      record['id']))

        with open('GDrive.avro', 'wb') as out:
            writer(out, parsed_schema, records)


if __name__ == '__main__':
    main()
```

**Comment by scottbelden** [comment]
Could you provide the full stack trace? Also, try modifying this part:

```python
        with open('GDrive.avro', 'wb') as out:
            writer(out, parsed_schema, records)
```

to be:

```python
        with open('GDrive.avro', 'wb') as out:
            from fastavro.validation import validate_many
            validate_many(records, parsed_schema)
            writer(out, parsed_schema, records)
```

Doing both of those should provide some more helpful debugging information.

**Comment by JulianScherp** [comment]
After the modification the full trace is

Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/GDriveTest/Avro.py", line 284, in <module>
    main()
  File "C:/Users/User/PycharmProjects/GDriveTest/Avro.py", line 279, in main
    validate_many(records, parsed_schema)
  File "fastavro/_validation.pyx", line 240, in fastavro._validation.validate_many
  File "fastavro/_validation.pyx", line 252, in fastavro._validation.validate_many
fastavro._validate_common.ValidationError: [

  "Field(GDrive.imageMediaMetadata.imageMediaMetadata.location) is None expected {'type': 'array', 'items': {'type': 'record', 'name': 'location', 'fields': [{'name': 'latitude', 'type': ['double', 'null']}, {'name': 'longtitude', 'type': ['double', 'null']}, {'name': 'altitude', 'type': ['double', 'null']}]}}",

  "GDrive.imageMediaMetadata is <{'width': 1024, 'height': 682, 'rotation': 0, 'time': '2018:08:07 10:06:24', 'cameraMake': 'PENTAX', 'cameraModel': 'PENTAX K-50', 'exposureTime': 0.001, 'aperture': 7.1, 'flashUsed': False, 'focalLength': 17.0, 'isoSpeed': 200, 'meteringMode': 'Pattern', 'sensor': 'One-chip color area', 'exposureMode': 'Auto', 'colorSpace': 'sRGB', 'whiteBalance': 'Auto', 'exposureBias': 0.0, 'subjectDistance': 3}> of type <class 'dict'> expected null",

  "GDrive.videoMediaMetadata.videoMediaMetadata.durationMillis is <2987> of type <class 'str'> expected long",
 
 "GDrive.videoMediaMetadata.videoMediaMetadata.durationMillis is <2987> of type <class 'str'> expected null",
  
"GDrive.videoMediaMetadata is <{'width': 1920, 'height': 1080, 'durationMillis': '2987'}> of type <class 'dict'> expected null",

  "Field(GDrive.imageMediaMetadata.imageMediaMetadata.location) is None expected {'type': 'array', 'items': {'type': 'record', 'name': 'location', 'fields': [{'name': 'latitude', 'type': ['double', 'null']}, {'name': 'longtitude', 'type': ['double', 'null']}, {'name': 'altitude', 'type': ['double', 'null']}]}}",
  
"GDrive.imageMediaMetadata is <{'width': 981, 'height': 827, 'rotation': 0}> of type <class 'dict'> expected null",

  "Field(GDrive.imageMediaMetadata.imageMediaMetadata.location) is None expected {'type': 'array', 'items': {'type': 'record', 'name': 'location', 'fields': [{'name': 'latitude', 'type': ['double', 'null']}, {'name': 'longtitude', 'type': ['double', 'null']}, {'name': 'altitude', 'type': ['double', 'null']}]}}",
  
"GDrive.imageMediaMetadata is <{'width': 709, 'height': 1063, 'rotation': 0, 'time': '2019:12:02 13:57:02', 'cameraMake': 'NIKON CORPORATION', 'cameraModel': 'NIKON D700', 'exposureTime': 0.008, 'aperture': 10.0, 'flashUsed': False, 'focalLength': 95.0, 'isoSpeed': 200, 'meteringMode': 'Spot', 'sensor': 'One-chip color area', 'exposureMode': 'Manual', 'colorSpace': 'sRGB', 'whiteBalance': 'Manual', 'exposureBias': 3.6666667, 'maxApertureValue': 4.0, 'subjectDistance': 0, 'lens': '24.0-120.0 mm f/4.0'}> of type <class 'dict'> expected null"
]

**Comment by JulianScherp** [comment]
Okay I found the mistakes using the new trace

the videoMediaMetadata.durationMillis had to be a string, even though google (2nd Link) states, it would be a long.

and I forgot to declare the default value for MediaMetadata.location.

Thank you so much for your help!

**Comment by scottbelden** [comment]
Great! I was just in the middle of typing out the problem areas but sounds like you already found them out.
