### ISSUE TITLE
Error when json encoding in loaded schema only if fields are nullable

### ISSUE THREAD

**Issue by r-archer37** [fastavro/fastavro#443]
I have been running up against an error trying to use JSON encoding with a schema that is defined across multiple files and has nullable fields all the way down. I'd like help sorting out if this is a problem in how schemas are parsed, how json encoding is done, or if it's a problem with my use of those. I've created a reproducible example that is necessarily broken out across a few files.

In addition to sharing everything below, I've also made an ad-hoc github repo to hold the necessary files and explanation of what's been observed: https://github.com/r-archer37/fastavro_error_mre

As pasted below, we encounter an error when calling `fastavro.json_writer`. However, if we alter the schema such that there are non-nullable fields in both `test.MultiBroadcaster.avsc` and `test.Broadcaster.avsc` then we no longer encounter that error.

Python version: 3.7.3
Fastavro version: 0.23.5

Python code:
```python
import json
import fastavro
from fastavro.schema import load_schema

INPUT_FILE = 'test_weather_data.json'
OUTPUT_FILE = 'test_weather_data.txt'
SCHEMA_TO_USE = 'Weather.avsc'

schema = load_schema(SCHEMA_TO_USE)


def fastavro_encode(schema, file_name, data):
    with open(file_name, 'w') as out:
        fastavro.json_writer(out, schema, data)


def fastavro_decode(schema, file_name):
    with open(file_name, 'r') as fo:
        my_reader = fastavro.json_reader(fo, schema)
        for record in my_reader:
            print(record)


fastavro_encode(schema,
                OUTPUT_FILE,
                [json.loads(open(INPUT_FILE, 'r').read())])

fastavro_decode(schema, OUTPUT_FILE)
```

`test_weather_data.json`:
```json
{
    "temperature": 99,
    "multibroadcaster": {
        "broadcaster": {
            "presenterName": "Pat",
            "presenterId": "2468ACE"
        }
    },
    "station": {
        "stationId": "13579BDF",
        "stationName": "Local"
    },
    "time": 1234567890
}
```

`Weather.avsc`:
```json
{
    "doc": "A weather reading.",
    "name": "Weather",
    "namespace": "test",
    "type": "record",
    "fields": [
        {"name": "temperature", "type": "int"},
        {"name": "time", "type": ["null", "long"], "default": null},
        {"name": "multibroadcaster", "type": ["null", "test.MultiBroadcaster"],
            "default": null
        },
        {"name": "station", "type": ["null", "test.Station"], "default": null}
    ]
}
```

`test.Station.avsc`
```json
{
    "namespace": "test",
    "type": "record",
    "name": "Station",
    "fields": [
        {"name": "stationId", "type": "string"},
        {"name": "stationName", "type": ["null", "string"], "default": null}
    ]
}
```

`test.MultiBroadcaster.avsc`
```json
{
    "namespace": "test",
    "type": "record",
    "name": "MultiBroadcaster",
    "fields": [
        {"name": "broadcaster", "type": ["null", "test.Broadcaster"], "default": null}
    ]
}
```

`test.Broadcaster.avsc`
```json
{
    "namespace": "test",
    "type": "record",
    "name": "Broadcaster",
    "fields": [
        {"name": "presenterId", "type": ["null", "string"], "default": null},
        {"name": "presenterName", "type": ["null", "string"], "default": null}
    ]
}
```

**Expected Output**
```python
{'temperature': 99, 'time': 1234567890, 'multibroadcaster': {'broadcaster': {'presenterId': '2468ACE', 'presenterName': 'Pat'}}, 'station': {'stationId': '13579BDF', 'stationName': 'Local'}}
```

**Actual Output**
```
Traceback (most recent call last):
  File "weather_avro.py", line 27, in <module>
    [json.loads(open(INPUT_FILE, 'r').read())])
  File "weather_avro.py", line 15, in fastavro_encode
    fastavro.json_writer(out, schema, data)
  File "/opt/conda/lib/python3.7/site-packages/fastavro/json_write.py", line 46, in json_writer
    return writer(AvroJSONEncoder(fo), schema, records)
  File "/opt/conda/lib/python3.7/site-packages/fastavro/_write_py.py", line 600, in writer
    output.flush()
  File "/opt/conda/lib/python3.7/site-packages/fastavro/_write_py.py", line 484, in flush
    self.encoder.flush()
  File "/opt/conda/lib/python3.7/site-packages/fastavro/io/json_encoder.py", line 72, in flush
    self._parser.flush()
  File "/opt/conda/lib/python3.7/site-packages/fastavro/io/parser.py", line 140, in flush
    self.action_function(top)
  File "/opt/conda/lib/python3.7/site-packages/fastavro/io/json_encoder.py", line 78, in do_action
    self.write_object_end()
  File "/opt/conda/lib/python3.7/site-packages/fastavro/io/json_encoder.py", line 158, in write_object_end
    self._pop()
  File "/opt/conda/lib/python3.7/site-packages/fastavro/io/json_encoder.py", line 50, in _pop
    prev_current[prev_key] = self._current
TypeError: unhashable type: 'list'
```

**Comment by scottbelden** [comment]
Thanks for the detailed report. I'll try to see what can be done, but I think the main problem is probably `load_schema`.

At the moment, if all the schemas are combined (like they would normally be in a real schema) I believe it works as expected.

For example, if I define `test.All.avsc` as this:

```
{
    "doc": "A weather reading.",
    "name": "Weather",
    "namespace": "test",
    "type": "record",
    "fields": [
        {"name": "temperature", "type": "int"},
        {"name": "time", "type": ["null", "long"], "default": null},
        {"name": "multibroadcaster", "type": [
            "null",
            {
                "namespace": "test",
                "type": "record",
                "name": "MultiBroadcaster",
                "fields": [
                    {"name": "broadcaster", "type": [
                        "null",
                        {
                            "namespace": "test",
                            "type": "record",
                            "name": "Broadcaster",
                            "fields": [
                                {"name": "presenterId", "type": ["null", "string"], "default": null},
                                {"name": "presenterName", "type": ["null", "string"], "default": null}
                            ]
                        }
                    ], "default": null}
                ]
            }
        ], "default": null
        },
        {"name": "station", "type": [
            "null",
            {
                "namespace": "test",
                "type": "record",
                "name": "Station",
                "fields": [
                    {"name": "stationId", "type": "string"},
                    {"name": "stationName", "type": ["null", "string"], "default": null}
                ]
            }
        ], "default": null}
    ]
}
```

And then in your repo's `weather_avro.py` I add these lines:

```python
from fastavro.schema import parse_schema
with open("test.All.avsc") as fp:
	s = json.load(fp)
schema = parse_schema(s)
```

Then it seems to work for me.

**Comment by r-archer37** [comment]
Thanks for validating! I've been trying to avoid dealing with the schema as a single blob because the message I want to parse is defined over 12 files, some of which define objects that occur more than once in the message - in other words a monster! Being able to manage these parts in discrete files is very attractive.
