### ISSUE TITLE
Schema resolution incorrectly failing for union with null and complex type

### ISSUE THREAD

**Issue by faph** [fastavro/fastavro#489]
In the following case, a schema resolution error is thrown while it should not.

Demonstrated with a producer using `schema_1` which is a record type containing a **union field of null and another record**. A consumer attempts to read this with `schema_2` which is exactly the same as `schema_1` except that it has a `doc` attribute on the union field. So, canonically, the schemas are the same.

```python
schema_1 = {
    "type": "record",
    "namespace": "ns1",
    "name": "Person",
    "fields": [
        {
            "name": "address",
            "type": [  # The union field...
                "null", # ...of null...
                {
                    "type": "record", # ...and a record
                    "namespace": "ns1",
                    "name": "Address",
                    "fields": [
                        {
                            "name": "city",
                            "type": "string",
                        },
                    ],
                },
            ],
        },
    ],
}
schema_2 = copy.deepcopy(schema_1)
schema_2["fields"][0]["type"][1]["doc"] = "An address"   # A small, immaterial change.

person = {
    "address": {
        "city": "Glasgow",
    },
}
fo = io.BytesIO()
# Simulate a producer with schema v1.
fastavro.schemaless_writer(fo=fo, schema=schema_1, record=person)
fo.seek(0)

# Simulate a consumer which has schema v2.
# Throws SchemaResolutionError.
fastavro.schemaless_reader(fo=fo, writer_schema=schema_1, reader_schema=schema_2)  
```

**Comment by faph** [comment]
Output:

```shell
Traceback (most recent call last):
...
    fastavro.schemaless_reader(fo=fo, writer_schema=schema_1, reader_schema=schema_2)
  File "fastavro\_read.pyx", line 969, in fastavro._read.schemaless_reader
  File "fastavro\_read.pyx", line 981, in fastavro._read.schemaless_reader
  File "fastavro\_read.pyx", line 652, in fastavro._read._read_data
  File "fastavro\_read.pyx", line 531, in fastavro._read.read_record
  File "fastavro\_read.pyx", line 644, in fastavro._read._read_data
  File "fastavro\_read.pyx", line 445, in fastavro._read.read_union
  File "fastavro\_read.pyx", line 68, in fastavro._read.match_types
  File "fastavro\_read.pyx", line 122, in fastavro._read.match_schemas
fastavro._read_common.SchemaResolutionError: Schema mismatch: {'type': 'record', 'name': 'ns1.Address', 'fields': [{'name': 'city', 'type': 'string'}]} is not null
```

**Comment by faph** [comment]
I'm using fastavro v1.0.0.post1. Looks like this may have been resolved in later versions?

**Comment by faph** [comment]
Yes it has, thanks!
