### ISSUE TITLE
1.3.4: Failing test on i686 + armv7hl: OverflowError: mktime argument out of range

### ISSUE THREAD

**Issue by sanjayankur31** [fastavro/fastavro#526]
Hello,

While updating the package on Fedora, we're seeing some tests failing on 32 bit architectures (i686 + armv7hl):

```
=================================== FAILURES ===================================
____________ test_problematic_timestamp_millis_naive_time[my_date1] ____________
Traceback (most recent call last):
  File "/builddir/build/BUILD/fastavro-1.3.4/tests/test_timezone.py", line 231, in test_problematic_timestamp_millis_naive_time
    assert_naive_datetime_equal_to_tz_datetime(
  File "/builddir/build/BUILD/fastavro-1.3.4/tests/conftest.py", line 26, in assert_naive_datetime_equal_to_tz_datetime
    microseconds = int(time.mktime(naive_datetime.timetuple())) * 1000 * 1000
OverflowError: mktime argument out of range
____________ test_problematic_timestamp_millis_naive_time[my_date2] ____________
Traceback (most recent call last):
  File "/builddir/build/BUILD/fastavro-1.3.4/tests/test_timezone.py", line 231, in test_problematic_timestamp_millis_naive_time
    assert_naive_datetime_equal_to_tz_datetime(
  File "/builddir/build/BUILD/fastavro-1.3.4/tests/conftest.py", line 26, in assert_naive_datetime_equal_to_tz_datetime
    microseconds = int(time.mktime(naive_datetime.timetuple())) * 1000 * 1000
OverflowError: mktime argument out of range
=========================== short test summary info ============================
FAILED tests/test_timezone.py::test_problematic_timestamp_millis_naive_time[my_date1]
FAILED tests/test_timezone.py::test_problematic_timestamp_millis_naive_time[my_date2]
=================== 2 failed, 551 passed, 4 skipped in 3.30s ===================
```

Here's the complete build log for the i686 build:
[fastavro-1.3.4-i686-build.txt](https://github.com/fastavro/fastavro/files/6217317/fastavro-1.3.4-i686-build.txt)

Here's the test build: https://koji.fedoraproject.org/koji/taskinfo?taskID=64732752

Cheers,

**Comment by scottbelden** [comment]
Does Fedora still support 32 bit architectures? We don't test against 32 bit anymore. Is it possible in the fedora build system to mark a package as 64 bit only?

**Comment by sanjayankur31** [comment]
Hello: yes, it isn't a primary architecture, but we still do support armv7hl and i686. 

I'll go disable the 32bit builds now. (we just make sure we check with upstream first).

Thanks very much. Closing this one.
