### ISSUE TITLE
avro can parse while fastavro can't

### ISSUE THREAD

**Issue by lamehost** [fastavro/fastavro#528]
Dear maintainers,

I  have found a case where [avro](https://pypi.org/project/avro/) can parse payloads that fastavro can't.

Please see the script below:
```
import io
import avro.schema
import avro.io
import fastavro
import json


SCHEMA = """
{
   "fields" : [
      {
         "name" : "log_type",
         "type" : {
            "type" : "string"
         }
      },
      {
         "name" : "seq",
         "type" : {
            "type" : "long"
         }
      },
      {
         "name" : "timestamp",
         "type" : {
            "type" : "string"
         }
      },
      {
         "name" : "event_type",
         "type" : {
            "type" : "string"
         }
      },
      {
         "name" : "writer_id",
         "type" : {
            "type" : "string"
         }
      },
      {
         "name" : "afi",
         "type" : {
            "type" : "int"
         }
      },
      {
         "name" : "safi",
         "type" : {
            "type" : "int"
         }
      },
      {
         "name" : "ip_prefix",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "string"
            }
         ]
      },
      {
         "name" : "rd",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "string"
            }
         ]
      },
      {
         "name" : "bgp_nexthop",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "string"
            }
         ]
      },
      {
         "name" : "as_path",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "string"
            }
         ]
      },
      {
         "name" : "as_path_id",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "long"
            }
         ]
      },
      {
         "name" : "comms",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "string"
            }
         ]
      },
      {
         "name" : "ecomms",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "string"
            }
         ]
      },
      {
         "name" : "lcomms",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "string"
            }
         ]
      },
      {
         "name" : "origin",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "string"
            }
         ]
      },
      {
         "name" : "local_pref",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "long"
            }
         ]
      },
      {
         "name" : "med",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "long"
            }
         ]
      },
      {
         "name" : "aigp",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "long"
            }
         ]
      },
      {
         "name" : "psid_li",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "long"
            }
         ]
      },
      {
         "name" : "label",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "string"
            }
         ]
      },
      {
         "name" : "peer_ip",
         "type" : {
            "type" : "string"
         }
      },
      {
         "name" : "peer_tcp_port",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "int"
            }
         ]
      },
      {
         "name" : "timestamp_arrival",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "string"
            }
         ]
      },
      {
         "name" : "bmp_router",
         "type" : {
            "type" : "string"
         }
      },
      {
         "name" : "bmp_router_port",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "int"
            }
         ]
      },
      {
         "name" : "bmp_msg_type",
         "type" : {
            "type" : "string"
         }
      },
      {
         "name" : "is_in",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "int"
            }
         ]
      },
      {
         "name" : "is_filtered",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "int"
            }
         ]
      },
      {
         "name" : "is_loc",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "int"
            }
         ]
      },
      {
         "name" : "is_post",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "int"
            }
         ]
      },
      {
         "name" : "is_out",
         "type" : [
            {
               "type" : "null"
            },
            {
               "type" : "int"
            }
         ]
      }
   ],
   "name" : "bmp_msglog_rm",
   "type" : "record"
}
"""

DATA = io.BytesIO(b'\x0cupdate\x84\r42021-03-30 08:14:34.000000\x06log\x12default/1\x02\x02\x02\x18192.0.2.0/24\x00\x02\x1e192.168.124.253\x02\n64586\x00\x00\x00\x00\x02\x02i\x00\x00\x00\x00\x00\x1e192.168.124.253\x02\x00\x0242021-03-30 08:14:34.325331\x1a192.168.85.69\x02\xbc\xdb\x04\x1aroute_monitor\x02\x02\x00\x00\x02\x00\x00')


# AVRO
print('TESTING AVRO')
parsed_schema = avro.schema.parse(SCHEMA)
DATA.seek(0)
decoded_bytes = avro.io.BinaryDecoder(DATA)
reader = avro.io.DatumReader(parsed_schema)
parsed_data = reader.read(decoded_bytes)
print(parsed_data)


# FASTAVRO
print()
print('TESTING FASTAVRO')
parsed_schema = fastavro.schema.parse_schema(json.loads(SCHEMA))
DATA.seek(0)
fastavro.validate(DATA, parsed_schema)
```

Here's what happens if i run it on my laptop:
```
$ python -V
Python 3.9.2
$ pip freeze | grep avro
avro==1.10.2
fastavro==1.3.4
$ python aa.py 
TESTING AVRO
{'log_type': 'update', 'seq': 834, 'timestamp': '2021-03-30 08:14:34.000000', 'event_type': 'log', 'writer_id': 'default/1', 'afi': 1, 'safi': 1, 'ip_prefix': '192.0.2.0/24', 'rd': None, 'bgp_nexthop': '192.168.124.253', 'as_path': '64586', 'as_path_id': None, 'comms': None, 'ecomms': None, 'lcomms': None, 'origin': 'i', 'local_pref': None, 'med': None, 'aigp': None, 'psid_li': None, 'label': None, 'peer_ip': '192.168.124.253', 'peer_tcp_port': 0, 'timestamp_arrival': '2021-03-30 08:14:34.325331', 'bmp_router': '192.168.85.69', 'bmp_router_port': 38622, 'bmp_msg_type': 'route_monitor', 'is_in': 1, 'is_filtered': None, 'is_loc': None, 'is_post': 0, 'is_out': None}

TESTING FASTAVRO
Traceback (most recent call last):
  File "/home/marco/santa/bmp-aggregator/aa.py", line 337, in <module>
    fastavro.validate(DATA, parsed_schema)
  File "fastavro/_validation.pyx", line 259, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 265, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 254, in fastavro._validation._validate
fastavro._validate_common.ValidationError: [
  " is <<_io.BytesIO object at 0x7f79045fdb30>> of type <class '_io.BytesIO'> expected {'__fastavro_parsed': True, '__named_schemas': {'bmp_msglog_rm': {'__fastavro_parsed': True, '__named_schemas': {'bmp_msglog_rm': {'type': 'record', 'name': 'bmp_msglog_rm', 'fields': [{'name': 'log_type', 'type': {'type': 'string'}}, {'name': 'seq', 'type': {'type': 'long'}}, {'name': 'timestamp', 'type': {'type': 'string'}}, {'name': 'event_type', 'type': {'type': 'string'}}, {'name': 'writer_id', 'type': {'type': 'string'}}, {'name': 'afi', 'type': {'type': 'int'}}, {'name': 'safi', 'type': {'type': 'int'}}, {'name': 'ip_prefix', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'rd', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'bgp_nexthop', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'as_path', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'as_path_id', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'comms', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'ecomms', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'lcomms', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'origin', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'local_pref', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'med', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'aigp', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'psid_li', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'label', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'peer_ip', 'type': {'type': 'string'}}, {'name': 'peer_tcp_port', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'timestamp_arrival', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'bmp_router', 'type': {'type': 'string'}}, {'name': 'bmp_router_port', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'bmp_msg_type', 'type': {'type': 'string'}}, {'name': 'is_in', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'is_filtered', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'is_loc', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'is_post', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'is_out', 'type': [{'type': 'null'}, {'type': 'int'}]}]}}, 'type': 'record', 'name': 'bmp_msglog_rm', 'fields': [{'name': 'log_type', 'type': {'type': 'string'}}, {'name': 'seq', 'type': {'type': 'long'}}, {'name': 'timestamp', 'type': {'type': 'string'}}, {'name': 'event_type', 'type': {'type': 'string'}}, {'name': 'writer_id', 'type': {'type': 'string'}}, {'name': 'afi', 'type': {'type': 'int'}}, {'name': 'safi', 'type': {'type': 'int'}}, {'name': 'ip_prefix', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'rd', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'bgp_nexthop', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'as_path', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'as_path_id', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'comms', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'ecomms', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'lcomms', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'origin', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'local_pref', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'med', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'aigp', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'psid_li', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'label', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'peer_ip', 'type': {'type': 'string'}}, {'name': 'peer_tcp_port', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'timestamp_arrival', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'bmp_router', 'type': {'type': 'string'}}, {'name': 'bmp_router_port', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'bmp_msg_type', 'type': {'type': 'string'}}, {'name': 'is_in', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'is_filtered', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'is_loc', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'is_post', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'is_out', 'type': [{'type': 'null'}, {'type': 'int'}]}]}}, 'type': 'record', 'name': 'bmp_msglog_rm', 'fields': [{'name': 'log_type', 'type': {'type': 'string'}}, {'name': 'seq', 'type': {'type': 'long'}}, {'name': 'timestamp', 'type': {'type': 'string'}}, {'name': 'event_type', 'type': {'type': 'string'}}, {'name': 'writer_id', 'type': {'type': 'string'}}, {'name': 'afi', 'type': {'type': 'int'}}, {'name': 'safi', 'type': {'type': 'int'}}, {'name': 'ip_prefix', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'rd', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'bgp_nexthop', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'as_path', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'as_path_id', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'comms', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'ecomms', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'lcomms', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'origin', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'local_pref', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'med', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'aigp', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'psid_li', 'type': [{'type': 'null'}, {'type': 'long'}]}, {'name': 'label', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'peer_ip', 'type': {'type': 'string'}}, {'name': 'peer_tcp_port', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'timestamp_arrival', 'type': [{'type': 'null'}, {'type': 'string'}]}, {'name': 'bmp_router', 'type': {'type': 'string'}}, {'name': 'bmp_router_port', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'bmp_msg_type', 'type': {'type': 'string'}}, {'name': 'is_in', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'is_filtered', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'is_loc', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'is_post', 'type': [{'type': 'null'}, {'type': 'int'}]}, {'name': 'is_out', 'type': [{'type': 'null'}, {'type': 'int'}]}]}"
]

```

Payload and schema where generated by [PMACCT](https://github.com/pmacct/pmacct/blob/7c1980e069b88191ebd9fca465c6bd6308c02db8/docs/BGP_BMP_METRICS.md).

**Comment by lamehost** [comment]
As a side note, here's the output when i try to read rather than to validate:
```
TESTING FASTAVRO
Traceback (most recent call last):
  File "/home/marco/santa/bmp-aggregator/aa.py", line 337, in <module>
    print("Valid: %s" % fastavro.reader(DATA, parsed_schema))
  File "fastavro/_read.pyx", line 1126, in fastavro._read.reader.__init__
  File "fastavro/_read.pyx", line 1072, in fastavro._read.file_reader.__init__
  File "fastavro/_read.pyx", line 807, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 667, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 791, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 522, in fastavro._read.read_map
  File "fastavro/_read.pyx", line 353, in fastavro._read.read_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 0: invalid start byte
```

**Comment by scottbelden** [comment]
`validate` expects the first argument to be a record (usually a python dictionary), not the serialized binary. So it definitely wouldn't work in this case.

The binary you have is not an avro container file that includes the schema, but rather just the serialized bytes without the schema. To be able to read this in `fastavro` you want to use `schemaless_reader`.

If we change the last line of your original script to this:

```python
record = fastavro.schemaless_reader(DATA, parsed_schema)
print(record)
```

Then it works.

**Comment by lamehost** [comment]
Thanks!
