### ISSUE TITLE
Inconsistent behavior 0-D numpy arrays

### ISSUE THREAD

**Issue by ksunden** [fastavro/fastavro#531]
0-D numpy arrays are a bit of a weird edge case...

Mostly they are just scalars which are wrapped in the "ndarray" type, but they act as scalars in many contexts.

In fact, when encoded with fastavro, they actually already work perfectly fine in some cases:

```python
>>> a = np.array(1123.)
>>> fo = BytesIO()
>>> b = fastavro.schemaless_writer(fo, "float", a)
>>> fo.seek(0)
0
>>> fastavro.schemaless_reader(fo, "float")
1123.0
```

(I absolutely do not care about reading it out with the ndarray wrapping in this case, I just have some functions which return the wrapped version and would prefer not to have to track down every time they are passed into fastavro)

However, when wrapped in a union schema for instance:
```python
>>> b = fastavro.schemaless_writer(fo, ["string", "float"], a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fastavro/_write.pyx", line 735, in fastavro._write.schemaless_writer
    write_data(tmp, record, schema, named_schemas, "")
  File "fastavro/_write.pyx", line 418, in fastavro._write.write_data
    return write_union(fo, datum, schema, named_schemas, fname)
  File "fastavro/_write.pyx", line 326, in fastavro._write.write_union
    raise ValueError(
ValueError: array(1123.) (type <class 'numpy.ndarray'>) do not match ['string', 'float']
```

I think this stems from the validate function, which is not called if the schema is known (it just blindly tries, and because it works, e.g. float(a) == 1123.0 and the cython equivalent, nothing complains) but when in a union it tries to validate first.

```python
>>> fastavro.validate(a, "float")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fastavro/_validation.pyx", line 259, in fastavro._validation.validate
    cpdef validate(object datum, object schema, str field="",
  File "fastavro/_validation.pyx", line 263, in fastavro._validation.validate
    return _validate(datum, parsed_schema, named_schemas, field, raise_errors)
  File "fastavro/_validation.pyx", line 254, in fastavro._validation._validate
    raise ValidationError(ValidationErrorData(datum, schema, field))
fastavro._validate_common.ValidationError: [
  " is <1123.0> of type <class 'numpy.ndarray'> expected float"
  ```
  
  Perhaps the correct answer is "wont fix", the workaround is trivial (just calling `float()`), but wondered if maintainers/other users here had ideas of how to elegantly check.

**Comment by scottbelden** [comment]
The only way I could see supporting something like this would be to allow users to patch the validation functions (similar to how we allow modifying the logical readers/writers). This is already kind of possible if you are running without cython (like on pypy) as you could do something like this:

```python
import numpy as np
from io import BytesIO
import fastavro

def new_float_validation(*args, **kwargs):
    return True

fastavro.validation._validation.VALIDATORS['float'] = new_float_validation

a = np.array(1123.)
fo = BytesIO()
b = fastavro.schemaless_writer(fo, ["string", "float"], a)
fo.seek(0)
print(fastavro.schemaless_reader(fo, ["string", "float"]))
# 1123.0
```

But this won't work with the cython code because `VALIDATORS` doesn't exist and it's probably not possible to patch the function if it's defined as a `cdef`.

I'm probably leaning on the won't fix side as it seems like a custom logical type would probably be the more appropriate path rather than messing with the validator functions, but I'll leave it open for now to think about a bit more.
