### ISSUE TITLE
It's not possible to read a record with a new, but compatible schema

### ISSUE THREAD

**Issue by pawelrubin** [fastavro/fastavro#550]
Consider the following piece of code
```python
import io

from fastavro import schemaless_reader, schemaless_writer


old_schema = {
    "type": "record",
    "name": "my_schema",
    "fields": [
        {"name": "foo", "type": "string"},
    ],
}

new_compatible_schema = {
    "type": "record",
    "name": "my_schema",
    "fields": [
        {"name": "foo", "type": "string"},
        {"name": "nullable_bar", "type": ["null", "string"], "default": None},
    ],
}


valid_record = {"foo": "foo", "foo2": 123}

output_stream = io.BytesIO()
schemaless_writer(output_stream, schema=old_schema, record=valid_record)

input_stream = io.BytesIO(output_stream.getvalue())
payload = schemaless_reader(
    input_stream,
    writer_schema=old_schema,
    reader_schema=new_compatible_schema,
)

print(payload)
```
It works well, successfully printing
```python
{'foo': 'foo', 'nullable_bar': None}
```

However, providing only the `reader_schema` should be sufficient to read the record, as the new schema is fully compatible.

Unfortunately, it's not possible to read the record having only the new, compatible schema.
Trying to read the record with the `new_compatible_schema` as the `writer_schema` results in an error.

```python
...
payload = schemaless_reader(
    input_stream,
    new_compatible_schema,
)
```
```shell
Traceback (most recent call last):
  File "<hidden>/test.py", line 30, in <module>
    payload = schemaless_reader(
  File "fastavro/_read.pyx", line 1158, in fastavro._read.schemaless_reader
  File "fastavro/_read.pyx", line 1170, in fastavro._read.schemaless_reader
  File "fastavro/_read.pyx", line 820, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 678, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 812, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 586, in fastavro._read.read_union
  File "fastavro/_read.pyx", line 242, in fastavro._read.read_long
StopIteration
```

**Comment by scottbelden** [comment]
This is a common misunderstanding with the Avro specification. Looking at the default value notes under [Complex Types](https://avro.apache.org/docs/current/spec.html#schema_complex) we see the following text:

`A default value for this field, only used when reading instances that lack the field for schema evolution purposes. The presence of a default value does not make the field optional at encoding time.`

So the default value is only ever considered for cases where there is schema evolution (both a writer and reader schema). If there is just a writer schema, that default value should be written when the record is encoded and therefore it is expected to be there when the record is decoded.

**Comment by pawelrubin** [comment]
How to handle this case then?

```python
fastavro.validate(valid_record, schema=new_compatible_schema)
```

passes. So I think it should be possible to decode such a record.

**Comment by scottbelden** [comment]
`validate` is not quite an apples to apples comparison since it is used more for writing records rather than reading records.

I also probably left out some information when I referenced the specification. Even though the specification states `The presence of a default value does not make the field optional at encoding time`, this library does actually allow a user to write a record that is missing fields. For example, this currently works:

```python
import io

from fastavro import schemaless_reader, schemaless_writer

new_compatible_schema = {
    "type": "record",
    "name": "my_schema",
    "fields": [
        {"name": "foo", "type": "string"},
        {"name": "nullable_bar", "type": ["null", "string"], "default": None},
    ],
}


valid_record = {"foo": "foo"}

output_stream = io.BytesIO()
schemaless_writer(output_stream, schema=new_compatible_schema, record=valid_record)
```

Even though according to the spec we should force the user to supply a record like `{"foo": "foo", "nullable_bar": None}`.

However, when we write out the binary, it still includes the fact that the `nullable_bar` field exists. This can be seen when running this script:

```python
import io

from fastavro import schemaless_reader, schemaless_writer

old_schema = {
    "type": "record",
    "name": "my_schema",
    "fields": [
        {"name": "foo", "type": "string"},
    ],
}

new_compatible_schema = {
    "type": "record",
    "name": "my_schema",
    "fields": [
        {"name": "foo", "type": "string"},
        {"name": "nullable_bar", "type": ["null", "string"], "default": None},
    ],
}


valid_record = {"foo": "foo"}

output_stream = io.BytesIO()
schemaless_writer(output_stream, schema=old_schema, record=valid_record)

print("binary written with old schema:")
print(output_stream.getvalue())

print("")

output_stream = io.BytesIO()
schemaless_writer(output_stream, schema=new_compatible_schema, record=valid_record)

print("binary written with new compatible schema:")
print(output_stream.getvalue())
```

Which prints out the following:

```
binary written with old schema:
b'\x06foo'

binary written with new compatible schema:
b'\x06foo\x00'
```

So when decoding we still need to have a binary string that includes the values for all fields (even if they have defaults).

**Comment by pawelrubin** [comment]
Current behavior makes it impossible to use some [compatibility rules](https://docs.confluent.io/platform/current/schema-registry/avro.html#summary).

Without the ability to decode records encoded with an old, but compatible (in the [**FULL_TRANSITIVE**](https://docs.confluent.io/platform/current/schema-registry/avro.html#full-compatibility) sense for example), there is no way to match the following requirement:
> For example, if there are three schemas for a subject that change in order X-2, X-1, and X then FULL_TRANSITIVE compatibility ensures that consumers using the new schema X can process data written by producers using schema X, X-1, or X-2, and that data written by producers using the new schema X can be processed by consumers using schema X, X-1, or X-2.

Is this a misinterpretation on the Apicurio side, and such compatibility guarantee is not possible, or the **fastavro** is too strict in this scenario?

**Comment by scottbelden** [comment]
It is possible to do schema evolution (and you have an example in the original post), but you need both the original schema that was used when writing and the new schema used for reading.

This issue seems pretty similar to https://issues.apache.org/jira/browse/AVRO-1661. In that issue, someone has an old schema that was used to write some binary and wanted to read that binary using only the new schema. But Avro doesn't support that. To do schema evolution, both the old and the new schemas have to be provided.

**Comment by pawelrubin** [comment]
Got it. 

So if one wants to read the binary with a schema that is different from the schema that has been used to encode the binary, they have to use both.

I was a bit confused with the Avro documentation, but now I get the idea. 

I think to resolve this issue, I'll have to either include the schema or the version of the schema in the message, together with data. I'll probably go with the latter, as including the schema would make the payload much bigger.

@scottbelden thank you for the quick and patient response and the detailed explanation! 🎖️

**Comment by pawelrubin** [comment]
There is, however, some room for improvements in the *fastavro* library. I think the error could be more descriptive. The `reader` could handle such a scenario and gracefully raise some custom, meaningful exception, instead of the `StopIteration`. What do you think?

**Comment by scottbelden** [comment]
I agree about trying to better detect the problem with a meaningful error message. I can try to take a look and see what can be done there.
