### ISSUE TITLE
Test suite failures on Python 3.8

### ISSUE THREAD

**Issue by samuela** [fastavro/fastavro#558]
I'm finding that the test suite passes without issue on Python 3.9, but there are some odd failures on Python 3.8. Here's the pytest output:
```
============================= test session starts ==============================
platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
SEED is 1631658071.1164587
rootdir: /build/source, configfile: pytest.ini
collected 585 items / 1 deselected / 584 selected                              

tests/test_aliases.py .......                                            [  1%]
tests/test_appendable.py .....                                           [  2%]
tests/test_block_reader.py ....                                          [  2%]
tests/test_canonical_form.py .......................................     [  9%]
tests/test_complex.py .....                                              [ 10%]
tests/test_compression.py .......sss..                                   [ 12%]
tests/test_fastavro.py ................................................. [ 20%]
.....................ss.................................s.............   [ 32%]
tests/test_fingerprint.py .............................................. [ 40%]
................................................................         [ 51%]
tests/test_json.py ....................                                  [ 54%]
tests/test_logical_types.py ...........................................  [ 62%]
tests/test_main_cli.py FFFFF                                             [ 63%]
tests/test_promotion.py .....                                            [ 64%]
tests/test_schema.py ................................................    [ 72%]
tests/test_schema_evolution.py ......................................... [ 79%]
....................................................                     [ 88%]
tests/test_schemaless.py ......                                          [ 89%]
tests/test_str_py3.py ..                                                 [ 89%]
tests/test_timezone.py ..............                                    [ 91%]
tests/test_types.py ..............                                       [ 94%]
tests/test_utils.py ...                                                  [ 94%]
tests/test_validation.py ..........................                      [ 99%]
tests/test_write_block.py ....                                           [100%]

=================================== FAILURES ===================================
____________________________ test_cli_record_output ____________________________
Traceback (most recent call last):
  File "/build/source/tests/test_main_cli.py", line 29, in test_cli_record_output
    result_output = subprocess.check_output(given_cmd_args).decode().splitlines()
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/bin/python3.8', '/build/source/tests/../fastavro/__main__.py', '/build/source/tests/avro-files/weather.avro']' returned non-zero exit status 1.
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/build/source/tests/../fastavro/__main__.py", line 3, in <module>
    import json
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/json/__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/json/decoder.py", line 3, in <module>
    import re
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/re.py", line 124, in <module>
    import enum
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/build/source/fastavro/types.py", line 2, in <module>
    from typing import Union, List, Dict
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/typing.py", line 23, in <module>
    import contextlib
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/contextlib.py", line 7, in <module>
    from types import MethodType
ImportError: cannot import name 'MethodType' from partially initialized module 'types' (most likely due to a circular import) (/build/source/fastavro/types.py)
____________________________ test_cli_stream_input _____________________________
Traceback (most recent call last):
  File "/build/source/tests/test_main_cli.py", line 51, in test_cli_stream_input
    subprocess.check_output(given_cmd_args, stdin=given_stdin_stream)
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/bin/python3.8', '/build/source/tests/../fastavro/__main__.py', '-']' returned non-zero exit status 1.
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/build/source/tests/../fastavro/__main__.py", line 3, in <module>
    import json
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/json/__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/json/decoder.py", line 3, in <module>
    import re
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/re.py", line 124, in <module>
    import enum
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/build/source/fastavro/types.py", line 2, in <module>
    from typing import Union, List, Dict
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/typing.py", line 23, in <module>
    import contextlib
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/contextlib.py", line 7, in <module>
    from types import MethodType
ImportError: cannot import name 'MethodType' from partially initialized module 'types' (most likely due to a circular import) (/build/source/fastavro/types.py)
____________________________ test_cli_arg_metadata _____________________________
Traceback (most recent call last):
  File "/build/source/tests/test_main_cli.py", line 68, in test_cli_arg_metadata
    result_output = subprocess.check_output(given_cmd_args).decode()
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/bin/python3.8', '/build/source/tests/../fastavro/__main__.py', '--metadata', '/build/source/tests/avro-files/testDataFileMeta.avro']' returned non-zero exit status 1.
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/build/source/tests/../fastavro/__main__.py", line 3, in <module>
    import json
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/json/__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/json/decoder.py", line 3, in <module>
    import re
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/re.py", line 124, in <module>
    import enum
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/build/source/fastavro/types.py", line 2, in <module>
    from typing import Union, List, Dict
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/typing.py", line 23, in <module>
    import contextlib
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/contextlib.py", line 7, in <module>
    from types import MethodType
ImportError: cannot import name 'MethodType' from partially initialized module 'types' (most likely due to a circular import) (/build/source/fastavro/types.py)
_____________________________ test_cli_arg_schema ______________________________
Traceback (most recent call last):
  File "/build/source/tests/test_main_cli.py", line 92, in test_cli_arg_schema
    result_output = subprocess.check_output(given_cmd_args).decode()
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/bin/python3.8', '/build/source/tests/../fastavro/__main__.py', '--schema', '/build/source/tests/avro-files/weather.avro']' returned non-zero exit status 1.
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/build/source/tests/../fastavro/__main__.py", line 3, in <module>
    import json
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/json/__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/json/decoder.py", line 3, in <module>
    import re
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/re.py", line 124, in <module>
    import enum
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/build/source/fastavro/types.py", line 2, in <module>
    from typing import Union, List, Dict
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/typing.py", line 23, in <module>
    import contextlib
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/contextlib.py", line 7, in <module>
    from types import MethodType
ImportError: cannot import name 'MethodType' from partially initialized module 'types' (most likely due to a circular import) (/build/source/fastavro/types.py)
_____________________________ test_cli_arg_codecs ______________________________
Traceback (most recent call last):
  File "/build/source/tests/test_main_cli.py", line 105, in test_cli_arg_codecs
    result_output = subprocess.check_output(given_cmd_args).decode()
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/bin/python3.8', '/build/source/tests/../fastavro/__main__.py', '--codecs']' returned non-zero exit status 1.
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/build/source/tests/../fastavro/__main__.py", line 3, in <module>
    import json
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/json/__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/json/decoder.py", line 3, in <module>
    import re
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/re.py", line 124, in <module>
    import enum
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/build/source/fastavro/types.py", line 2, in <module>
    from typing import Union, List, Dict
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/typing.py", line 23, in <module>
    import contextlib
  File "/nix/store/66p7i56lg3zzp7nj6g0fywb704ihp4iy-python3-3.8.11/lib/python3.8/contextlib.py", line 7, in <module>
    from types import MethodType
ImportError: cannot import name 'MethodType' from partially initialized module 'types' (most likely due to a circular import) (/build/source/fastavro/types.py)
=========================== short test summary info ============================
FAILED tests/test_main_cli.py::test_cli_record_output - subprocess.CalledProc...
FAILED tests/test_main_cli.py::test_cli_stream_input - subprocess.CalledProce...
FAILED tests/test_main_cli.py::test_cli_arg_metadata - subprocess.CalledProce...
FAILED tests/test_main_cli.py::test_cli_arg_schema - subprocess.CalledProcess...
FAILED tests/test_main_cli.py::test_cli_arg_codecs - subprocess.CalledProcess...
============ 5 failed, 573 passed, 6 skipped, 1 deselected in 3.70s ============
```

**Comment by scottbelden** [comment]
I wonder if your environment is set up slightly differently? We have regression tests for python 3.8 on linux (both cpython and pypy) and they seem to be running normally:

CPython: https://github.com/fastavro/fastavro/runs/3596220326?check_suite_focus=true
Pypy: https://github.com/fastavro/fastavro/runs/3596220542?check_suite_focus=true

**Comment by samuela** [comment]
> I wonder if your environment is set up slightly differently? We have regression tests for python 3.8 on linux (both cpython and pypy) and they seem to be running normally:

Hmm, yeah it's possible. Seems like the only possible explanation since CI is passing. I can't think of what difference would cause these kinds of errors. The nix-build environment attempts to be as hermetic as possible so things like network access and writing to certain parts of the file system are not allowed. But those don't strike me as likely suspects here...

**Comment by Alessandro-Barbieri** [comment]
Same on gentoo, see
https://bugs.gentoo.org/815649
https://815649.bugs.gentoo.org/attachment.cgi?id=742383

**Comment by ksunden** [comment]
Are you running from within the source folder (where there is a `types.py` that would be imported rather than the stdlib `types` module? (and imports the stdlib types module, thus circular import/unfinished import)

**Comment by scottbelden** [comment]
That is strange because the CI (as well as my own local way of testing) does the same thing: https://github.com/fastavro/fastavro/blob/master/.github/workflows/build_linux.yml#L34-L35

**Comment by scottbelden** [comment]
@samuela @Alessandro-Barbieri I wonder if https://github.com/fastavro/fastavro/pull/730 fixes this issue...

**Comment by hroncok** [comment]
I believe my PR should fix this. Python 3.12 says it cannot import GenericAlias, and here we see MethodType, but that is just a slight difference in the standard library code -- the cause is the same: `types.py` from the parent directory of `__main__.py` shadows the standard library `types` module.
