### ISSUE TITLE
Logical types are not written to named_schemas in parse_schema

### ISSUE THREAD

**Issue by Artimi** [fastavro/fastavro#576]
Hi,

I've encountered an unexpected behavior using `fastavro.schema.parse_schema`. 

I would expect that this
```python
def test_using_named_schemas_to_handle_references_logical_type():
    location = {
        "name": "Latitude",
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 4,
        "scale": 2,
    }
    weather = {
        "name": "Weather",
        "type": "record",
        "fields": [{"name": "of", "type": "Location"}],
    }

    named_schemas = {}
    parse_schema(location, named_schemas)
    parse_schema(weather, named_schemas)
```
works but it fails with
```
Traceback (most recent call last):
  File "/home/artimi/projects/fastavro/tests/test_schema.py", line 514, in test_using_named_schemas_to_handle_references_logical_type
    parse_schema(weather, named_schemas)
  File "fastavro/_schema.pyx", line 106, in fastavro._schema.parse_schema
    return _parse_schema(
  File "fastavro/_schema.pyx", line 245, in fastavro._schema._parse_schema
    parse_field(field, namespace, expand, names, named_schemas)
  File "fastavro/_schema.pyx", line 290, in fastavro._schema.parse_field
    parsed_field["type"] = _parse_schema(
  File "fastavro/_schema.pyx", line 129, in fastavro._schema._parse_schema
    raise UnknownType(schema)
fastavro._schema_common.UnknownType: Location
```

The problem is that `Location` is not saved to the `named_schemas` as other types (non-logical) would (see `test_using_named_schemas_to_handle_references`).

I was able to work around it by storing the parsed logical type to `named_schema` manually but this can be issue for other users.

```python
    named_schemas = {}
    parsed_location = parse_schema(location, named_schemas)
    named_schemas["Location"] = parsed_location
    parse_schema(weather, named_schemas)
```
Also, I did not check other types after the workaround so there can be problem with them as well.

**Comment by Artimi** [comment]
Hi I've found another problem:

```Python
def test_parse_schema_array_references():
    location = {
        "name": "Location",
        "type": "record",
        "fields": [{"name": "city", "type": "long"}],
    }
    weather = {
        "name": "weather",
        "type": "array",
        "items": ["Location"],
    }

    named_schemas = {}
    fastavro.parse_schema(location, named_schemas)
    parsed_schema = fastavro.parse_schema(weather, named_schemas)

    records = [[{"city": 1}]]
    new_records = roundtrip(parsed_schema, records)

    assert records == new_records
```
Results in
```
Traceback (most recent call last):
  File "/home/artimi/projects/fastavro/tests/test_fastavro.py", line 266, in test_parse_schema_array_references
    new_records = roundtrip(parsed_schema, records)
  File "/home/artimi/projects/fastavro/tests/test_fastavro.py", line 35, in roundtrip
    fastavro.writer(new_file, schema, records)
  File "fastavro/_write.pyx", line 720, in fastavro._write.writer
    output = Writer(
  File "fastavro/_write.pyx", line 607, in fastavro._write.Writer.__init__
    self.schema = parse_schema(schema, self._named_schemas)
  File "fastavro/_schema.pyx", line 106, in fastavro._schema.parse_schema
    return _parse_schema(
  File "fastavro/_schema.pyx", line 190, in fastavro._schema._parse_schema
    parsed_schema["items"] = _parse_schema(
  File "fastavro/_schema.pyx", line 115, in fastavro._schema._parse_schema
    _parse_schema(
  File "fastavro/_schema.pyx", line 129, in fastavro._schema._parse_schema
    raise UnknownType(schema)
fastavro._schema_common.UnknownType: Location
```

This one can be parsed but `parsed_schema` is missing
```
{'type': 'array', 'items': ['Location']}
```

I've found a workaround for this too: if you manually add the `__named_schemas` and `__fastavro_parsed` to the schema and use it also as a reader_schema it will work.

```python
def test_parse_schema_array_references():
    location = {
        "name": "Location",
        "type": "record",
        "fields": [{"name": "city", "type": "long"}],
    }
    weather = {
        "name": "weather",
        "type": "array",
        "items": ["Location"],
    }

    named_schemas = {}
    fastavro.parse_schema(location, named_schemas)
    parsed_schema = fastavro.parse_schema(weather, named_schemas)

    records = [[{"city": 1}]]

    parsed_schema["__fastavro_parsed"] = True
    parsed_schema["__named_schemas"] = named_schemas

    new_records = roundtrip(parsed_schema, records, reader_schema = parsed_schema)

    assert records == new_records
```

**Comment by scottbelden** [comment]
As for the first case:

```python
def test_using_named_schemas_to_handle_references_logical_type():
    location = {
        "name": "Location",
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 4,
        "scale": 2,
    }
    weather = {
        "name": "Weather",
        "type": "record",
        "fields": [{"name": "of", "type": "Location"}],
    }

    named_schemas = {}
    parse_schema(location, named_schemas)
    parse_schema(weather, named_schemas)
```

This doesn't work because the avro specification only states that records, enums, and fixed types are named. So the name for this decimal/bytes type is essentially ignored because that name is treated as just an extra attribute rather than an actual avro name.

**Comment by scottbelden** [comment]
> Hi I've found another problem:
> 
> ```python
> def test_parse_schema_array_references():
>     location = {
>         "name": "Location",
>         "type": "record",
>         "fields": [{"name": "city", "type": "long"}],
>     }
>     weather = {
>         "name": "weather",
>         "type": "array",
>         "items": ["Location"],
>     }
> 
>     named_schemas = {}
>     fastavro.parse_schema(location, named_schemas)
>     parsed_schema = fastavro.parse_schema(weather, named_schemas)
> 
>     records = [[{"city": 1}]]
>     new_records = roundtrip(parsed_schema, records)
> 
>     assert records == new_records
> ```
> 
> Results in
> 
> ```
> Traceback (most recent call last):
>   File "/home/artimi/projects/fastavro/tests/test_fastavro.py", line 266, in test_parse_schema_array_references
>     new_records = roundtrip(parsed_schema, records)
>   File "/home/artimi/projects/fastavro/tests/test_fastavro.py", line 35, in roundtrip
>     fastavro.writer(new_file, schema, records)
>   File "fastavro/_write.pyx", line 720, in fastavro._write.writer
>     output = Writer(
>   File "fastavro/_write.pyx", line 607, in fastavro._write.Writer.__init__
>     self.schema = parse_schema(schema, self._named_schemas)
>   File "fastavro/_schema.pyx", line 106, in fastavro._schema.parse_schema
>     return _parse_schema(
>   File "fastavro/_schema.pyx", line 190, in fastavro._schema._parse_schema
>     parsed_schema["items"] = _parse_schema(
>   File "fastavro/_schema.pyx", line 115, in fastavro._schema._parse_schema
>     _parse_schema(
>   File "fastavro/_schema.pyx", line 129, in fastavro._schema._parse_schema
>     raise UnknownType(schema)
> fastavro._schema_common.UnknownType: Location
> ```
> 
> This one can be parsed but `parsed_schema` is missing
> 
> ```
> {'type': 'array', 'items': ['Location']}
> ```
> 
> I've found a workaround for this too: if you manually add the `__named_schemas` and `__fastavro_parsed` to the schema and use it also as a reader_schema it will work.
> 
> ```python
> def test_parse_schema_array_references():
>     location = {
>         "name": "Location",
>         "type": "record",
>         "fields": [{"name": "city", "type": "long"}],
>     }
>     weather = {
>         "name": "weather",
>         "type": "array",
>         "items": ["Location"],
>     }
> 
>     named_schemas = {}
>     fastavro.parse_schema(location, named_schemas)
>     parsed_schema = fastavro.parse_schema(weather, named_schemas)
> 
>     records = [[{"city": 1}]]
> 
>     parsed_schema["__fastavro_parsed"] = True
>     parsed_schema["__named_schemas"] = named_schemas
> 
>     new_records = roundtrip(parsed_schema, records, reader_schema = parsed_schema)
> 
>     assert records == new_records
> ```

I took a look at this and I think there is a change that can be made to make it work for the writer, but it would fail when reading unless explicitly passed in the `parsed_schema` like you did. This is because the `parse_schema` doesn't actually try to inject named schemas.

I think an alternative option would be to use some of the recently added functionality which allows for loading schemas and handles the injection of named schemas. An example looks like this:

```python
import fastavro
from fastavro.repository import AbstractSchemaRepository
from io import BytesIO

def roundtrip(schema, records, **reader_kwargs):
    new_file = BytesIO()
    fastavro.writer(new_file, schema, records)
    new_file.seek(0)

    reader = fastavro.reader(new_file, **reader_kwargs)

    new_records = list(reader)
    return new_records


class LocalSchemaRepository(AbstractSchemaRepository):
    def __init__(self, schemas):
        self.schemas = schemas

    def load(self, subject):
        return self.schemas.get(subject)

repo = LocalSchemaRepository(
    {
        "Location": {
            "name": "Location",
            "type": "record",
            "fields": [{"name": "city", "type": "long"}],
        },
        "weather": {
            "type": "array",
            "items": ["Location"],
        },
    }
)

parsed_schema = fastavro.schema.load_schema("weather", repo=repo)
print(parsed_schema)

records = [[{"city": 1}]]
new_records = roundtrip(parsed_schema, records)

assert records == new_records
```

NOTE: I haven't created a release for this new feature yet, so you'd have to work directly off the `master` branch for now. Let me know if you think something like this would help and if so I'll try to get a release cut shortly.

**Comment by Artimi** [comment]
That's a cool feature! Since I've found a workaround for the problem I'm not in need for the feature. Also, I have many linked schemata in our system. I acquaint them iteratively: I try to load the schema, it raises UnknownType schemaXYZ, I try to load schemaXYZ, ... Maybe it would be possible with the SchemaRepository IDK. I think we can keep this open and if someone else needs the feature then you will have more use-cases.

**Comment by scottbelden** [comment]
Gotcha. Yeah, the `load_schema` was put in to try to help will parsing dependent schemas, but if you have something that works then stick with that.
