### ISSUE TITLE
parse_schema() fails on a valid union

### ISSUE THREAD

**Issue by jchia** [fastavro/fastavro#590]
`parse_schema()` fails on the following schema passed to it as a string literal:
```
[
    {
        "type": "record",
        "name": "Foo",
        "fields": [
            {
                "name": "x",
                "type": "long"
            }
        ]
    },
    {
        "type": "record",
        "name": "Bar",
        "fields": [
            {
                "name": "x",
                "type": "long"
            }
        ]
    }
]
```

This is the stack trace:
```
Traceback (most recent call last):
  File "py/dump-md.py", line 163, in <module>
    parsed_schema = parse_schema(_SCHEMA2)
  File "fastavro/_schema.pyx", line 107, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 130, in fastavro._schema._parse_schema
fastavro._schema_common.UnknownType: 
[
    {
        "type": "record",
        "name": "Foo",
        "fields": [
            {
                "name": "x",
                "type": "long"
            }
        ]
    },
    {
        "type": "record",
        "name": "Bar",
        "fields": [
            {
                "name": "x",
                "type": "long"
            }
        ]
    }
]
```

The schema is valid and `parse_schema()` should just work.

**Comment by jchia** [comment]
Never mind, there was confusion about the expected input type.
