### ISSUE TITLE
Union types not working correctly on json reader

### ISSUE THREAD

**Issue by arop** [fastavro/fastavro#599]
I've encountered a bug while using `json_reader` for union types.
Here's the traceback

```
Traceback (most recent call last):
  File "issue2.py", line 30, in <module>
    test()
  File "issue2.py", line 26, in test
    for r in re:
  File "/Users/andrepires/Desktop/fastavro-test/venv/lib/python3.8/site-packages/fastavro/_read_py.py", line 1066, in _elems
    yield read_data(
  File "/Users/andrepires/Desktop/fastavro-test/venv/lib/python3.8/site-packages/fastavro/_read_py.py", line 675, in read_data
    data = reader_fn(
  File "/Users/andrepires/Desktop/fastavro-test/venv/lib/python3.8/site-packages/fastavro/_read_py.py", line 542, in read_record
    record[field["name"]] = read_data(
  File "/Users/andrepires/Desktop/fastavro-test/venv/lib/python3.8/site-packages/fastavro/_read_py.py", line 675, in read_data
    data = reader_fn(
  File "/Users/andrepires/Desktop/fastavro-test/venv/lib/python3.8/site-packages/fastavro/_read_py.py", line 459, in read_union
    index = decoder.read_index()
  File "/Users/andrepires/Desktop/fastavro-test/venv/lib/python3.8/site-packages/fastavro/io/json_decoder.py", line 216, in read_index
    label, data = self._current[self._key].popitem()
AttributeError: 'bool' object has no attribute 'popitem'
```

Here's an example on how to reproduce.

```python
import io
import json

import fastavro


AVRO_SCHEMA = {
    "namespace": "com.issue",
    "name": "Issue",
    "type": "record",
    "fields": [
        {"name": "external", "default": None, "type": ["null", "boolean"]},
    ],
}

ISSUE_OBJECT = {
    'external': True,
}


def test():
    s = fastavro.parse_schema(AVRO_SCHEMA)
    object_bytes = io.BytesIO(json.dumps(ISSUE_OBJECT).encode())
    re = fastavro.json_reader(fo=object_bytes, schema=s)
    for r in re:
        print(r)


test()
```

My guess is that on `json_decoder.py` - `read_index` you need to change `label, data = self._current[self._key].popitem()`.

I changed to `label, data = self._current.popitem()` but the correct `label` is needed on the following lines 
```python
index = alternative_symbol.labels.index(label)
symbol = alternative_symbol.get_symbol(index)
```

On my example, I would say that the label needs to be `"boolean"`, so not sure on how to accomplish that

**Comment by scottbelden** [comment]
The problem here is that `ISSUE_OBJECT` is not the correct JSON encoded avro. The JSON encoding is basically what you would expect except in the case of unions. For that case, the specification states that non-null unions should instead be a new object with the type as the key. See the relevant section here: https://avro.apache.org/docs/current/spec.html#json_encoding

If we use the `json_writer`, we can see how the `ISSUE_OBJECT` should look when encoded:

```python
import io
import json

import fastavro


AVRO_SCHEMA = {
    "namespace": "com.issue",
    "name": "Issue",
    "type": "record",
    "fields": [
        {"name": "external", "default": None, "type": ["null", "boolean"]},
    ],
}



ISSUE_OBJECT = {
    'external': True,
}


def test():
    s = fastavro.parse_schema(AVRO_SCHEMA)
    sio = io.StringIO()
    fastavro.json_writer(sio, s, [ISSUE_OBJECT])
    print(sio.getvalue())


test()
```

This should print out `{"external": {"boolean": true}}`

So if you wanted to make your script work, the JSON you are trying to read must match that format. An updated version of the script that works looks like this:

```python
import io
import json

import fastavro


AVRO_SCHEMA = {
    "namespace": "com.issue",
    "name": "Issue",
    "type": "record",
    "fields": [
        {"name": "external", "default": None, "type": ["null", "boolean"]},
    ],
}

# ISSUE_OBJECT = {
#     'external': True,
# }
ISSUE_OBJECT = {
    'external': {"boolean": True},
}


def test():
    s = fastavro.parse_schema(AVRO_SCHEMA)
    object_bytes = io.BytesIO(json.dumps(ISSUE_OBJECT).encode())
    re = fastavro.json_reader(fo=object_bytes, schema=s)
    for r in re:
        print(r)


test()
```

I hope that makes sense. It's a bit annoying that unions are handled this way and there is an issue on the Avro tracker about this and proposals to change or modify it: https://issues.apache.org/jira/browse/AVRO-1582
