### ISSUE TITLE
Unhashable type 'dict' during deserialization with a reader schema

### ISSUE THREAD

**Issue by choogeboom** [fastavro/fastavro#601]
I've been seeing the following error lately in one of my applications (fastavro version 1.4.10)

Error
```
packages/mep_serde/deserialize.py", line 256, in _deserialize_apache_avro_binary
          yield from fastavro.reader(binary_file, reader_schema=schema)
        File "fastavro/_read.pyx", line 996, in _iter_avro_records
        File "fastavro/_read.pyx", line 820, in fastavro._read._read_data
        File "fastavro/_read.pyx", line 699, in fastavro._read.read_record
        File "fastavro/_read.pyx", line 796, in fastavro._read._read_data
        File "fastavro/_read.pyx", line 443, in fastavro._read.read_array
        File "fastavro/_read.pyx", line 820, in fastavro._read._read_data
        File "fastavro/_read.pyx", line 699, in fastavro._read.read_record
        File "fastavro/_read.pyx", line 832, in fastavro._read._read_data
      TypeError: unhashable type: 'dict'
```

This only happens when I try to deserialize using a reader schema. Unfortunately, I've only been able to reproduce it with proprietary data, so I can't send you an actual avro file/schema in order to assist in debugging. I will say that this should _probably_ have been a schema resolution error, but I can't be sure because the schemas in question are very large. Sorry I can't offer any better information. Let me know if you have any questions about the data, and I'll try to answer to the best of my ability.

**Comment by scottbelden** [comment]
Are you using a reader schema when this happens? I think I can get the same type of error with this example:

```python
from fastavro import writer, reader, parse_schema
from io import BytesIO

schema = {
    "type": "record",
    "name": "test_record_named_type",
    "fields": [
        {
            "name": "test1",
            "type": {
                "type": "record",
                "name": "my_record",
                "fields": [
                    {
                        "name": "field1",
                        "type": "string",
                    }
                ],
            },
        },
        {
            "name": "test2",
            "type": "my_record",
        },
    ],
}
parsed_schema = parse_schema(schema)

records = [{"test1": {"field1": "foo"}, "test2": {"field1": "bar"}}]

bio = BytesIO()
writer(bio, parsed_schema, records)

bio.seek(0)

reader_schema = {
    "type": "record",
    "name": "test_record_named_type",
    "fields": [
        {
            "name": "test1",
            "type": {
                "type": "record",
                "name": "my_record",
                "fields": [
                    {
                        "name": "field1",
                        "type": "string",
                    }
                ],
            },
        },
        {
            "name": "test2",
            "type": {
                "type": "record",
                "name": "new_record",
                "fields": [
                    {
                        "name": "field1",
                        "type": "string",
                    }
                ]
            },
        },
    ],
}
parsed_reader = parse_schema(reader_schema)
for record in reader(bio, reader_schema=parsed_reader):
    print(record)
```

This happens when it gets to the `test2` field because in the first schema it is just a record name whereas in the reader schema it has changed to a dictionary.

Let me know if this is along the right path. I do agree that the error is unclear and so at a minimum that should be improved but there could also be a bug in the handling of a schema evolution.

**Comment by choogeboom** [comment]
Yeah, this only happens when I use a reader schema, and the schema doesn't match the writer schema. I can deserialize the same binary without a reader schema just fine.

**Comment by scottbelden** [comment]
Do you know if the reader schema does something similar to what I did (replace a named type with a type defined in a dictionary)?

Also, I don't know if it is sufficient anonymization, but there is an [`anonymize_schema` and a `generate_one` function](https://fastavro.readthedocs.io/en/latest/utils.html) that I wonder if you can try to use to provide the example schemas and data.

You would do something like this:

```python
anon_writer = anonymize_schema(writer_schema)
dummy_data = generate_one(anon_writer)

writer(out, anon_writer, [dummy_data])
out.seek(0)

anon_reader = anonymize_schema(reader_schema)
list(reader(out, reader_schema=anon_reader)  # This should hopefully still fail with the same error
```

If that still fails and the schemas and dummy_data are sufficiently masked and you feel comfortable posting it then that could help with the debugging process.

**Comment by choogeboom** [comment]
I didn't even know that those functions existed! Unfortunately `generate_one` didn't work

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/pyenv/versions/project/lib/python3.9/site-packages/fastavro/utils.py", line 108, in generate_one
    return next(generate_many(schema, 1))
  File "/pyenv/versions/project/lib/python3.9/site-packages/fastavro/utils.py", line 145, in generate_many
    parsed_schema = parse_schema(schema, named_schemas)
  File "fastavro/_schema.pyx", line 107, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 246, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 291, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 191, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 246, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 291, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 246, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 291, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 116, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 216, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 568, in fastavro._schema._validate_enum_symbols
fastavro._schema_common.SchemaParseException: Every symbol must match the regular expression [A-Za-z_][A-Za-z0-9_]*
```

I was able to anonymize the schemas though, and have attached them: [anonymized_schemas.zip](https://github.com/fastavro/fastavro/files/8741279/anonymized_schemas.zip)

**Comment by scottbelden** [comment]
I pushed a fix for the generate bug: https://github.com/fastavro/fastavro/commit/add8a99de6d5d6a24e003b6ff7ea3228f9065d4c

But the schemas you provided were very helpful. It looks like I was on the right track but I was able to confirm that the reader schema is trying to use the same record, but it is just the long form instead of the short name because of the way the schema was changed. For example, this produces the same bug:

```python
from fastavro import writer, reader, parse_schema
from io import BytesIO


schema = {
    "type": "record",
    "name": "test_record_named_type",
    "fields": [
        {
            "name": "test1",
            "type": {
                "type": "record",
                "name": "my_record",
                "fields": [
                    {
                        "name": "field1",
                        "type": "string",
                    }
                ],
            },
        },
        {
            "name": "test2",
            "type": "my_record",
        },
    ],
}
parsed_schema = parse_schema(schema)

records = [{"test1": {"field1": "foo"}, "test2": {"field1": "bar"}}]

bio = BytesIO()
writer(bio, parsed_schema, records)

bio.seek(0)

reader_schema = {
    "type": "record",
    "name": "test_record_named_type",
    "fields": [
        {
            "name": "test2",
            "type": {
                "type": "record",
                "name": "my_record",
                "fields": [
                    {
                        "name": "field1",
                        "type": "string",
                    }
                ],
            },
        },
    ],
}
parsed_reader = parse_schema(reader_schema)
for record in reader(bio, reader_schema=parsed_reader):
    print(record)
```

This should definitely be valid and works just fine with the apache avro library:

```python
import avro.schema
from avro.datafile import DataFileReader, DataFileWriter
from avro.io import DatumReader, DatumWriter

writer_schema = {
    "type": "record",
    "name": "test_record_named_type",
    "fields": [
        {
            "name": "test1",
            "type": {
                "type": "record",
                "name": "my_record",
                "fields": [
                    {
                        "name": "field1",
                        "type": "string",
                    }
                ],
            },
        },
        {
            "name": "test2",
            "type": "my_record",
        },
    ],
}

reader_schema = {
    "type": "record",
    "name": "test_record_named_type",
    "fields": [
        {
            "name": "test2",
            "type": {
                "type": "record",
                "name": "my_record",
                "fields": [
                    {
                        "name": "field1",
                        "type": "string",
                    }
                ],
            },
        },
    ],
}

records = [{"test1": {"field1": "foo"}, "test2": {"field1": "bar"}}]

with open("foo.avro", "wb") as fp:
    writer = DataFileWriter(fp,
                            DatumWriter(),
                            avro.schema.make_avsc_object(writer_schema))
    for record in records:
        writer.append(record)
    writer.flush()

with open("foo.avro", "rb") as fp:
    records = list(
        DataFileReader(
            fp,
            DatumReader(
                avro.schema.make_avsc_object(writer_schema),
                avro.schema.make_avsc_object(reader_schema),
            )
        )
    )

print(records)
```

I'll try to see if I can patch this up.

**Comment by choogeboom** [comment]
Excellent! Thanks so much for the fast response!

**Comment by scottbelden** [comment]
@choogeboom I believe https://github.com/fastavro/fastavro/pull/603 should resolve this. I'll probably merge it tomorrow.
