### ISSUE TITLE
fastavro 1.4.11 fails to reuse nested schemas

### ISSUE THREAD

**Issue by asfer** [fastavro/fastavro#608]
On `Python 3.9.9` with `fastavro 1.4.10` the following code is able to insert the 2 records as expected:

```
import tempfile
from pathlib import Path
from pprint import pprint
from textwrap import dedent

import fastavro

with tempfile.TemporaryDirectory() as tmp_dir:
    dir_path = Path(tmp_dir)

    with open(dir_path / 'namespace.match.avsc', 'w') as f:
        f.write(dedent("""
        {
            "name": "namespace.match",
            "type": "record",
            "fields": [
                {"name": "id", "type": "string"},
                {"name": "team1", "type": "namespace.team"},
                {"name": "team2", "type": "namespace.team"}
            ]
        }
        """))

    with open(dir_path / 'namespace.team.avsc', 'w') as f:
        f.write(dedent("""
        {
            "name": "namespace.team",
            "type": "record",
            "fields": [
                {"name": "name", "type": "string"}
            ]
        }
        """))

    schema = fastavro.schema.load_schema(str(dir_path / 'namespace.match.avsc'))

    record = {
        'id': '123',
        'team1': {'name': 'A'},
        'team2': {'name': 'B'}
    }
    with open(dir_path / 'result.avro', 'a+b') as f:
        fastavro.writer(f, schema, [record])
        fastavro.writer(f, schema, [record])

    with open(dir_path / 'result.avro', 'rb') as f:
        for r in fastavro.reader(f):
            pprint(r)
```

However, after `fastavro 1.4.11` it fails on the second writer call with:

```
Traceback (most recent call last):
  File "script.py", line 44, in <module>
    fastavro.writer(f, schema, [record])
  File "fastavro/_write.pyx", line 727, in fastavro._write.writer
  File "fastavro/_write.pyx", line 680, in fastavro._write.Writer.write
  File "fastavro/_write.pyx", line 422, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 366, in fastavro._write.write_record
  File "fastavro/_write.pyx", line 425, in fastavro._write.write_data
KeyError: 'namespace.team'

Process finished with exit code 1
```

**Comment by scottbelden** [comment]
Thanks for the easy to reproduce report. I'll push out `1.5.1` shortly.
