### ISSUE TITLE
`fastavro.write` does not persist `named_schemas`

### ISSUE THREAD

**Issue by mhils** [fastavro/fastavro#683]
When using `named_schemas`, `fastavro.write` does not include the children's schema in the header, which makes reading fail:

```python
import io
import fastavro

parent_schema = {
    "type": "record",
    "name": "Parent",
    "fields": [
        {
            "name": "child",
            "type": "Child"
        }
    ]
}
child_schema = {
    "type": "record",
    "name": "Child",
    "fields": []
}

named_schemas = {}
fastavro.schema.parse_schema(child_schema, named_schemas=named_schemas)
ps = fastavro.schema.parse_schema(parent_schema, named_schemas=named_schemas)

# Write to file...
buf = io.BytesIO()
fastavro.writer(buf, ps, [{"child": {}}])
print(buf.getvalue())
```
Note how the output does not include a definition for `Child`:
```
b'Obj\x01\x04\x14avro.codec\x08null\x16avro.schema\xa8\x01{"type": "record", "name": "Parent", "fields": [{"name": "child", "type": "Child"}]}\x001\x0e\xd2\xb7P\x0c)O\x8b\xa2\x0e \x14x\xc5\xb0\x02\x001\x0e\xd2\xb7P\x0c)O\x8b\xa2\x0e \x14x\xc5\xb0'
```

If we now try to read:
```python
# Read from file...
buf.seek(0)
(parent,) = fastavro.reader(buf, reader_schema=ps)
```
We get the following exception:
```python
Traceback (most recent call last):
  File "repro.py", line 32, in <module>
    (parent,) = fastavro.reader(buf, reader_schema=ps)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fastavro\_read.pyx", line 1081, in fastavro._read.reader.__init__
  File "fastavro\_read.pyx", line 1051, in fastavro._read.file_reader.__init__
  File "fastavro\_schema.pyx", line 119, in fastavro._schema.parse_schema
  File "fastavro\_schema.pyx", line 381, in fastavro._schema._parse_schema
  File "fastavro\_schema.pyx", line 449, in fastavro._schema.parse_field
  File "fastavro\_schema.pyx", line 238, in fastavro._schema._parse_schema
fastavro._schema_common.UnknownType: Child
```

A simple workaround for this toy example would be to set `expand=True`, but that fails once the model has any repeated fields. If I understand things correctly, we would need something like an `expand_schema(once=True)` method that is called by GenericWriter.

---------------------------------------------------

fastavro version: 1.7.3

**Comment by scottbelden** [comment]
Thanks for the bug report. There is an existing [`_inject_schema`](https://github.com/fastavro/fastavro/blob/106c78971f71ef0b02c41eaabdf86f2ba5b0d7d0/fastavro/_schema_py.py#L745) function that we use internally in the `load_schema` API that should handle this correctly, but it's not currently called during `parse_schema`.

So I think it should be fairly straight forward to fix once I have some free time.

If you need an immediate workaround, something like works:

```python
import io
import fastavro

class LocalSchemaRepository(fastavro.repository.AbstractSchemaRepository):
    def __init__(self, schemas):
        self.schemas = schemas

    def load(self, subject):
        return self.schemas.get(subject)

repo = LocalSchemaRepository(
    {
        "Parent": {
            "type": "record",
            "name": "Parent",
            "fields": [
                {
                    "name": "child",
                    "type": "Child"
                }
            ]
        },
        "Child": {
            "type": "record",
            "name": "Child",
            "fields": []
        },
    }
)

loaded_schema = fastavro.schema.load_schema("Parent", repo=repo)

# Write to file...
buf = io.BytesIO()
fastavro.writer(buf, loaded_schema, [{"child": {}}])
print(buf.getvalue())

# Read from file...
buf.seek(0)
(parent,) = fastavro.reader(buf, reader_schema=loaded_schema)
print(parent)
```

**Comment by enifsieus** [comment]
Experimenting with the LocalSchemaRepository workaround led to a different problem ...

```
import fastavro

import copy


class LocalSchemaRepository(fastavro.repository.AbstractSchemaRepository):
    def __init__(self, schemas):
        self.schemas = schemas

    def load(self, subject):
        return self.schemas.get(subject)


repo = LocalSchemaRepository(
    {
        "Parent": {
            "type": "record",
            "name": "Parent",
            "fields": [
                {"name": "child", "type": "Child"},
                {"name": "grandchild", "type": "GrandChild"}
            ],
        },
        "Cat": {
            "type": "record",
            "name": "Cat",
            "fields": []
        },
        "Child": {
            "type": "record",
            "name": "Child",
            "fields": [
                {"name": "cat", "type": "Cat"}
            ]
        },
        "GrandChild": {
            "type": "record",
            "name": "GrandChild",
            "fields": [
                {"name": "cat", "type": "Cat"}
            ],
        },
    }
)

print("Loading Child Schema...")
loaded_schema = fastavro.schema.load_schema("Child", repo=repo)
print("Loading GrandChild Schema...")
loaded_schema = fastavro.schema.load_schema("GrandChild", repo=repo)
print("Loading Parent Schema...")
loaded_schema = fastavro.schema.load_schema("Parent", repo=repo)
```

This leads to:

```
Loading Child Schema...
Loading GrandChild Schema...
Loading Parent Schema...
Traceback (most recent call last):
  File "fastavro/_schema.pyx", line 511, in fastavro._schema._parse_schema_with_repo
  File "fastavro/_schema.pyx", line 146, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 381, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 449, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 238, in fastavro._schema._parse_schema
fastavro._schema_common.UnknownType: Child

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fastavro/_schema.pyx", line 511, in fastavro._schema._parse_schema_with_repo
  File "fastavro/_schema.pyx", line 146, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 381, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 449, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 238, in fastavro._schema._parse_schema
fastavro._schema_common.UnknownType: GrandChild

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minimal.py", line 51, in <module>
    loaded_schema = fastavro.schema.load_schema("Parent", repo=repo)
  File "fastavro/_schema.pyx", line 483, in fastavro._schema.load_schema
  File "fastavro/_schema.pyx", line 491, in fastavro._schema._load_schema
  File "fastavro/_schema.pyx", line 530, in fastavro._schema._parse_schema_with_repo
  File "fastavro/_schema.pyx", line 530, in fastavro._schema._parse_schema_with_repo
  File "fastavro/_schema.pyx", line 511, in fastavro._schema._parse_schema_with_repo
  File "fastavro/_schema.pyx", line 146, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 381, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 449, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 381, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 449, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 368, in fastavro._schema._parse_schema
fastavro._schema_common.SchemaParseException: redefined named type: Cat
```

It's not immediately obvious to me what the shared state is, but repo=deepcopy(repo) for each load does seem to work in any order.
