### ISSUE TITLE
fastavro doesn't compile with Cython 3

### ISSUE THREAD

**Issue by eddie-scio** [fastavro/fastavro#701]
`Cython` is unpinned in `pyproject.toml`: https://github.com/fastavro/fastavro/blob/1.8.0/pyproject.toml#L5

3.0 was released today, and it fails to compile:
```
     running build_ext
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  writer_schema, named_schemas, offset, size, options,
              )
      
      
      class Block:
          def __init__(
          ^
      ------------------------------------------------------------
      
      fastavro/_read.pyx:950:4: Compiler crash in AnalyseDeclarationsTransform
      
      File 'ModuleNode.py', line 203, in analyse_declarations: ModuleNode(_read.pyx:1:0,
          doc = 'Python code for reading AVRO files',
          full_module_name = 'fastavro._read')
      File 'Nodes.py', line 393, in analyse_declarations: StatListNode(_read.pyx:10:0)
      File 'Nodes.py', line 393, in analyse_declarations: StatListNode(_read.pyx:949:0)
      File 'Nodes.py', line 5121, in analyse_declarations: PyClassDefNode(_read.pyx:949:0,
          name = 'Block')
      File 'Nodes.py', line 393, in analyse_declarations: StatListNode(_read.pyx:950:4)
      File 'Nodes.py', line 2710, in analyse_declarations: CFuncDefNode(_read.pyx:950:4,
          args = [...]/10,
          modifiers = [...]/0,
          outer_attrs = [...]/2,
          overridable = True,
          visibility = 'private')
      File 'Nodes.py', line 2721, in declare_cpdef_wrapper: CFuncDefNode(_read.pyx:950:4,
          args = [...]/10,
          modifiers = [...]/0,
          outer_attrs = [...]/2,
          overridable = True,
          visibility = 'private')
      File 'Nodes.py', line 2787, in call_self_node: CFuncDefNode(_read.pyx:950:4,
          args = [...]/10,
          modifiers = [...]/0,
          outer_attrs = [...]/2,
          overridable = True,
          visibility = 'private')
      
      Compiler crash traceback from this point on:
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/Cython/Compiler/Nodes.py", line 2787, in call_self_node
          type_entry = self.type.args[0].type.entry
      AttributeError: 'PyObjectType' object has no attribute 'entry'
      Compiling fastavro/_read.pyx because it changed.
      [1/1] Cythonizing fastavro/_read.pyx
      Traceback (most recent call last):
        File "/Users/eddiezhou/workspace/scio/python_scio/scio_env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/eddiezhou/workspace/scio/python_scio/scio_env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/eddiezhou/workspace/scio/python_scio/scio_env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 37, in <module>
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/l7/21y95v250mb3qjny7dzrm7pr0000gn/T/pip-build-env-6st80onk/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: fastavro/_read.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fastavro
Failed to build fastavro
```

Could we follow `hdbscan`'s example: https://github.com/scikit-learn-contrib/hdbscan/issues/600#issuecomment-1638710947
to unblock building?

**Comment by scottbelden** [comment]
Is the suggestion to pin `cython<3`? If so that makes sense to me and would be easy to push out.

**Comment by eddie-scio** [comment]
> Is the suggestion to pin `cython<3`? If so that makes sense to me and would be easy to push out.

That's right!  Like https://github.com/scikit-learn-contrib/hdbscan/commit/dd27600acb0ad1f96d5e5ba97513d316f2d646bc

**Comment by salman1993** [comment]
I am facing the same error

**Comment by scottbelden** [comment]
New release will be out shortly.

**Comment by kevinlinxc** [comment]
Thank you for the fast fix.

**Comment by eddie-scio** [comment]
Sorry for the nag -- I saw all the commits are in, any ETA until `1.8.1` is release on pypi?  Thank you Scott!

**Comment by scottbelden** [comment]
1.8.1 should be on pypi now.

**Comment by kevinlinxc** [comment]
Is there any workaround for users who are using older package versions? Apparently 1.7 and above breaks other stuff in our system.

**Comment by tvalentyn** [comment]
@kevinlinxc you should be able to add a dependency on `cython<3` as a workaround. For example:

` pip install 'cython<3' 'fastavro~=1.7.0'  `

**Comment by kevinlinxc** [comment]
That did not work on its own, as the Cython used for fastavro building is the latest regardless of what is installed locally (until today's release). Playing around with `--no-build-isolation` worked for me though, as described here: https://github.com/scikit-learn-contrib/hdbscan/issues/600#issuecomment-1638737876. Basically, the flag tells pip to use local dependencies.

**Comment by tonitajger** [comment]
Is there any plan on pinning `cpython<3` for older releases or do we need to rely on the above workaround? I'm encountering these issues on 1.6.1 and 1.5.2

**Comment by scottbelden** [comment]
There are no plans to make older releases with the fix so using the `--no-build-isolation` flag is probably necessary.
