### ISSUE TITLE
Two tests fail when the zlib implementation is zlib-ng

### ISSUE THREAD

**Issue by musicinmybrain** [fastavro/fastavro#740]
Fedora Linux is replacing [zlib](https://www.zlib.net/) with [zlib-ng](https://github.com/zlib-ng/zlib-ng); more information is [here](https://fedoraproject.org/wiki/Changes/ZlibNGTransition).

While `zlib-ng` in `zlib-compat` mode is API- and ABI-compatible with classic zlib, it does not guarantee identical compressed streams. (Nor does `zlib` across versions, but in practice its output has not changed in a long time.) As a result, the following two failures occur when the `zlib` implementation is `zlib-ng` because the compressed block sizes are slightly different:

```
=========================== short test summary info ============================
FAILED tests/test_block_reader.py::test_block_iteration_deflated_disk - asser...
FAILED tests/test_block_reader.py::test_block_iteration_deflated_memory - ass...
====== 2 failed, 668 passed, 4 skipped, 2 deselected, 1 warning in 2.54s =======
```

Perhaps it would be better to assert that the block size is less than the uncompressed size, or if you want to be stricter, less than some fairly close upper bound like 17000 or 20000 bytes.

Tested with fastavro 1.8.4 (since we are still working on packaging the `cramjam` dependency for 1.9.x). Full output of the failing tests to be posted in a follow-up comment.

**Comment by musicinmybrain** [comment]
```
=================================== FAILURES ===================================
______________________ test_block_iteration_deflated_disk ______________________
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
                                ^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/fastavro-1.8.4/_empty/tests/test_block_reader.py", line 85, in test_block_iteration_deflated_disk
    check_round_trip_deflated(write_to_disk=True)
  File "/builddir/build/BUILD/fastavro-1.8.4/_empty/tests/test_block_reader.py", line 69, in check_round_trip_deflated
    assert bytes == 16543
AssertionError: assert 16850 == 16543
_____________________ test_block_iteration_deflated_memory _____________________
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
                                ^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)  
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/fastavro-1.8.4/_empty/tests/test_block_reader.py", line 89, in test_block_iteration_deflated_memory
    check_round_trip_deflated(write_to_disk=False)
  File "/builddir/build/BUILD/fastavro-1.8.4/_empty/tests/test_block_reader.py", line 69, in check_round_trip_deflated
    assert bytes == 16543
AssertionError: assert 16850 == 16543
=============================== warnings summary ===============================
_empty/tests/test_logical_types.py::test_pandas_datetime
  /builddir/build/BUILD/fastavro-1.8.4/_empty/tests/test_logical_types.py:436: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
    datetime.datetime.utcnow().replace(tzinfo=timezone.utc)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_block_reader.py::test_block_iteration_deflated_disk - asser...
FAILED tests/test_block_reader.py::test_block_iteration_deflated_memory - ass...
====== 2 failed, 668 passed, 4 skipped, 2 deselected, 1 warning in 2.54s =======
```

**Comment by scottbelden** [comment]
Thanks for the heads up. I agree that we should remove the checks for the exact number of bytes. The real test should just be that it roundtrips correctly.

I'm assuming that something compressed with zlib-ng is still readable with the original zlib, right?

And I think this finally uncovers the mystery of https://github.com/fastavro/fastavro/issues/605. For the life of me I could never reproduce that issue but the number of bytes you have here match the ones in that issue so the difference must be that it was also using zlib-ng.

**Comment by musicinmybrain** [comment]
> I'm assuming that something compressed with zlib-ng is still readable with the original zlib, right?

Correct: they should always be happy to read each other’s byte streams. The compressors just don’t necessarily make identical choices, since that would be hard to guarantee and overly constraining on the implementation.

> And I think this finally uncovers the mystery of #605. For the life of me I could never reproduce that issue but the number of bytes you have here match the ones in that issue so the difference must be that it was also using zlib-ng.

🎉
