### ISSUE TITLE
Fastavro fastavro.schemaless_reader returns unexpected EOF (1.8.4)

### ISSUE THREAD

**Issue by galCohen88** [fastavro/fastavro#743]
We are running python 3.9.16 with `fastavro==1.8.2` for a while, calling `schemaless_reader` function. 

Once updating to `1.8.4` we started to get `EOFError` before end of actual content. 

`Traceback (most recent call last):
  File "fastavro/_read.pyx", line 1126, in fastavro._read.schemaless_reader
  File "fastavro/_read.pyx", line 1153, in fastavro._read.schemaless_reader
  File "fastavro/_read.pyx", line 743, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 616, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 735, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 526, in fastavro._read.read_union
  File "fastavro/_read.pyx", line 176, in fastavro._read.read_long
EOFError`

I'm not sure if it's even possible to reproduce in other envs, I wonder if anyone encountered this issue as well.

**Comment by mokshasoul** [comment]
Hi this was an issue here as well 👍🏼 
https://github.com/googleapis/python-bigquery-storage/pull/687

**Comment by scottbelden** [comment]
Yeah, I think this might be essentially the same issue.
