### ISSUE TITLE
Record that contain unions of other records with multiple levels seems not to work

### ISSUE THREAD

**Issue by marcosschroh** [fastavro/fastavro#807]
Hi,

It seems that `records` that have an union with multiple levels are not properly working. I would like to at least confirm if the following example is correct or not. For this use case I have records that are really similar to each other, so I will include the special `-type` attribute.

First let's do a simple use case that works as expected:

```python
import io
import fastavro


schema = {
  'type': 'record',
  'name': 'BranchOne', 
  'fields': [{
    'name': 'leaf', 
    'type': [
      {'type': 'record', 'name': 'LeafOne', 'fields': [{'name': 'name', 'type': 'string'}]}, 
      {'type': 'record', 'name': 'LeafTwo', 'fields': [{'name': 'name', 'type': 'string'}]}
    ]}
  ]
}

# To properly view it, the class representation is the following:
class LeafOne:
    name: str

class LeafTwo:
    name: str

class BranchOne:
    leaf: LeafOne | LeafTwo

# then serialize a payload 
payload = {'leaf': {'name': 'batman', '-type': 'LeafOne'}}

file_like_output = io.BytesIO()
fastavro.schemaless_writer(file_like_output, schema, payload)
print(file_like_output.getvalue())
# >>> b'\x00\x0cbatman'
```

Now if we introduce more  union levels it does not work:

```python
import io
import fastavro

schema = {
  "type": "record",
  "name": "RootSchema",
  "fields": [
    {
      "name": "branch",
      "type": [
        {
          "type": "record",
          "name": "BranchOne",
          "fields": [
            {
              "name": "leaf",
              "type": [
                {
                  "type": "record",
                  "name": "LeafOne",
                  "fields": [
                    {
                      "name": "name",
                      "type": "string"
                    }
                  ]
                },
                {
                  "type": "record",
                  "name": "LeafTwo",
                  "fields": [
                    {
                      "name": "name",
                      "type": "string"
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          "type": "record",
          "name": "BranchTwo",
          "fields": [
            {
              "name": "leaf",
              "type": [
                "LeafOne",
                "LeafTwo"
              ]
            }
          ]
        }
      ]
    }
  ]
}

# To properly view it, the class representation is the following:
class LeafOne:
    name: str


class LeafTwo:
    name: str


class BranchOne:
    leaf: LeafOne | LeafTwo


class BranchTwo:
    leaf: LeafOne | LeafTwo


class RootSchema:
    branch: BranchOne | BranchTwo


# check that the schema is valid
fastavro.parse_schema(schema)

# then serialize a payload 
payload = {'branch': {'leaf': {'name': 'batman', '-type': 'LeafOne'}, '-type': 'BranchOne'}}

file_like_output = io.BytesIO()
fastavro.schemaless_writer(file_like_output, schema, payload)
print(file_like_output.getvalue())

Traceback (most recent call last):
  File "/Users/marcosschroh/Projects/dataclasses-avroschema/models.py", line 139, in <module>
    fastavro.schemaless_writer(file_like_output, schema, payload)
  File "fastavro/_write.pyx", line 805, in fastavro._write.schemaless_writer
  File "fastavro/_write.pyx", line 459, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 403, in fastavro._write.write_record
  File "fastavro/_write.pyx", line 457, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 337, in fastavro._write.write_union
ValueError: {'leaf': {'name': 'batman', '-type': 'LeafOne'}, '-type': 'BranchOne'} (type <class 'dict'>) do not match [{'type': 'record', 'name': 'BranchOne', 'fields': [{'name': 'leaf', 'type': [{'type': 'record', 'name': 'LeafOne', 'fields': [{'name': 'name', 'type': 'string'}]}, {'type': 'record', 'name': 'LeafTwo', 'fields': [{'name': 'name', 'type': 'string'}]}]}]}, {'type': 'record', 'name': 'BranchTwo', 'fields': [{'name': 'leaf', 'type': ['LeafOne', 'LeafTwo']}]}] on field branch
```

Just to confirm, the `-type` attribute should be always next to the payload, right? Thanks

**Comment by marcosschroh** [comment]
Closing this because switching from injecting a "-type" marker to fastavro's [tuple notation](https://fastavro.readthedocs.io/en/latest/writer.html#using-the-tuple-notation-to-specify-which-branch-of-a-union-to-take) works properly as work around
